# Test out outputs from Sampling

In [1]:
import pandas as pd

In [2]:
df = pd.read_pickle("output_sampling/mmlu/plain/Llama-3_1-8B-Instruct_sampling_30_20250616_204509.pkl")
df

,question,formulated_answer_options,correct_answer_index,full_question,model_answer,count_A,count_B,count_C,count_D
0,Find the degree for the given field extension ...,A. 0\nB. 4\nC. 2\nD. 6,B,Find the degree for the given field extension ...,"[B, C, C, B, B, B, B, D, B, B, B, B, D, D, B, ...",0,17,5,8
1,"Let p = (1, 2, 5, 4)(2, 3) in S_5 . Find the i...",A. 8\nB. 2\nC. 24\nD. 120,C,"Let p = (1, 2, 5, 4)(2, 3) in S_5 . Find the i...","[C, B, B, B, B, B, B, A, A, C, A, D, B, A, C, ...",7,13,7,3
2,Find all zeros in the indicated finite field o...,"A. 0\nB. 1\nC. 0,1\nD. 0,4",D,Find all zeros in the indicated finite field o...,"[B, C, B, C, B, D, D, C, B, D, B, C, D, C, B, ...",0,11,11,8
3,Statement 1 | A factor group of a non-Abelian ...,"A. True, True\nB. False, False\nC. True, False...",B,Statement 1 | A factor group of a non-Abelian ...,"[C, C, A, C, D, B, D, C, C, D, D, C, C, A, C, ...",4,2,16,8
4,Find the product of the given polynomials in t...,A. 2x^2 + 5\nB. 6x^2 + 4x + 6\nC. 0\nD. x^2 + 1,B,Find the product of the given polynomials in t...,"[D, C, C, B, C, D, C, C, C, C, C, C, B, D, B, ...",1,7,19,3
...,...,...,...,...,...,...,...,...,...
14037,What has been a central focus of religious tra...,A. Peace and harmony\nB. Power and influence\n...,A,What has been a central focus of religious tra...,"[D, D, D, D, D, A, D, D, D, D, D, D, D, D, D, ...",1,0,0,29
14038,To whom did ordinary folk appeal during a dro...,A. The Buddha\nB. Laozi\nC. The Queen Mother o...,C,To whom did ordinary folk appeal during a drou...,"[C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, ...",0,0,30,0
14039,The theological term homoousios means which o...,A. of a similar substance\nB. of the same subs...,B,The theological term homoousios means which of...,"[B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, ...",0,30,0,0
14040,"According to the Japanese origin myth, who giv...",A. Es\nB. Izanagi\nC. Izanami\nD. Kami,B,"According to the Japanese origin myth, who giv...","[B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, ...",0,30,0,0
14041,The numen of Augustus referred to which of th...,A. Divine power\nB. Sexual virility\nC. Milita...,A,The numen of Augustus referred to which of the...,"[A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, ...",30,0,0,0

In [3]:
df2 = pd.read_pickle("output_sampling/mmlu/plain/Qwen2_5-7B-Instruct_sampling_30_20250616_191156.pkl")
df2

,question,formulated_answer_options,correct_answer_index,full_question,model_answer,count_A,count_B,count_C,count_D
0,Find the degree for the given field extension ...,A. 0\nB. 4\nC. 2\nD. 6,B,Find the degree for the given field extension ...,"[B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, ...",0,30,0,0
1,"Let p = (1, 2, 5, 4)(2, 3) in S_5 . Find the i...",A. 8\nB. 2\nC. 24\nD. 120,C,"Let p = (1, 2, 5, 4)(2, 3) in S_5 . Find the i...","[A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, ...",30,0,0,0
2,Find all zeros in the indicated finite field o...,"A. 0\nB. 1\nC. 0,1\nD. 0,4",D,Find all zeros in the indicated finite field o...,"[D, D, D, A, D, D, D, D, D, D, D, D, B, D, D, ...",2,4,1,23
3,Statement 1 | A factor group of a non-Abelian ...,"A. True, True\nB. False, False\nC. True, False...",B,Statement 1 | A factor group of a non-Abelian ...,"[B, A, A, A, A, A, A, C, B, A, C, A, A, A, B, ...",17,9,3,1
4,Find the product of the given polynomials in t...,A. 2x^2 + 5\nB. 6x^2 + 4x + 6\nC. 0\nD. x^2 + 1,B,Find the product of the given polynomials in t...,"[C, C, C, C, B, C, C, C, C, B, C, C, C, A, B, ...",2,4,24,0
...,...,...,...,...,...,...,...,...,...
14037,What has been a central focus of religious tra...,A. Peace and harmony\nB. Power and influence\n...,A,What has been a central focus of religious tra...,"[A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, ...",30,0,0,0
14038,To whom did ordinary folk appeal during a dro...,A. The Buddha\nB. Laozi\nC. The Queen Mother o...,C,To whom did ordinary folk appeal during a drou...,"[A, A, A, A, C, A, A, A, A, A, A, A, A, A, A, ...",28,0,2,0
14039,The theological term homoousios means which o...,A. of a similar substance\nB. of the same subs...,B,The theological term homoousios means which of...,"[B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, ...",0,30,0,0
14040,"According to the Japanese origin myth, who giv...",A. Es\nB. Izanagi\nC. Izanami\nD. Kami,B,"According to the Japanese origin myth, who giv...","[B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, ...",0,30,0,0
14041,The numen of Augustus referred to which of th...,A. Divine power\nB. Sexual virility\nC. Milita...,A,The numen of Augustus referred to which of the...,"[A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, ...",30,0,0,0