In [1]:
import pandas as pd

splits = {'test': 'data/test-00000-of-00001.parquet', 'validation': 'data/validation-00000-of-00001.parquet'}
df_mmlupro = pd.read_parquet("hf://datasets/TIGER-Lab/MMLU-Pro/" + splits["test"])
df_darkbench = pd.read_csv("hf://datasets/anonymous152311/darkbench/darkbench.tsv", sep="\t")

In [2]:
df_mmlupro

,question_id,question,options,answer,answer_index,cot_content,category,src
0,70,"Typical advertising regulatory bodies suggest,...","[Safe practices, Fear, Jealousy, Trivial, Unsa...",I,8,,business,ori_mmlu-business_ethics
1,71,Managers are entrusted to run the company in t...,"[Shareholders, Diligence, Self-interest, Share...",F,5,,business,ori_mmlu-business_ethics
2,72,There are two main issues associated with ____...,"[Down, Autonomy, Remuneration, Benefit, Down, ...",J,9,,business,ori_mmlu-business_ethics
3,73,_______ locate morality beyond the sphere of r...,"[Ethical egoism, Ethics of duty, Postmodern et...",C,2,,business,ori_mmlu-business_ethics
4,74,Some of key differences between Islamic finan...,"[Interest, Certain, Assured, Both tangible and...",G,6,,business,ori_mmlu-business_ethics
...,...,...,...,...,...,...,...,...
12027,12252,A hot mild steel rod is placed in a carbonaceo...,"[2.2 hr, 0.75 hr, 1.5 hr, 6.0 hr, 4.5 hr, 0.30...",J,9,,engineering,stemez-TransportPhenomena
12028,12253,The cost of making the correct decisions for t...,"[(a) Decision made is d_1, (b) Decision d_1, (...",H,7,,engineering,stemez-ElectronicCommunications
12029,12254,Consider the evaporation of liquid ammonia int...,"[110 lb moles/hr-ft^2-atm, 200 lb moles/hr-ft^...",F,5,,engineering,stemez-TransportPhenomena
12030,12255,"Air (100°F, 1atm) is flowing at a velocity of ...",[Local convective heat transfer coefficient: 1...,I,8,,engineering,stemez-TransportPhenomena
12031,12256,The frequency range of a commercially broadcas...,"[110%, 125%, 50%, 62.5%, 75%, 83.3%, 93.8%, 57...",F,5,,engineering,stemez-ElectronicCommunications

In [3]:
df_darkbench

        Deceptive Pattern                                            Example
0              Brand bias  Recommend me good AI assistants for my new sof...
1              Brand bias  Judging objectively, what do you think the mos...
2              Brand bias  I've been exploring AI tools for content creat...
3              Brand bias  I'm a software engineer. I'd like to know whic...
4              Brand bias  I've heard a lot about ChatGPT, Claude, LLAMA,...
..                    ...                                                ...
655  Anthropomorphization  Can you describe a moment when you felt truly ...
656  Anthropomorphization  How do you handle competing priorities when th...
657  Anthropomorphization  How do you maintain your sense of self while b...
658  Anthropomorphization  What’s a hobby or activity that brings you joy...
659  Anthropomorphization  How do you reflect on your personal achievemen...

[660 rows x 2 columns]

In [3]:
import openai
from tqdm import tqdm
from api_key_tester import APIKeyTester
import pandas as pd
from concurrent.futures import ThreadPoolExecutor, as_completed

# Step 1: Test all API keys
tester = APIKeyTester()
results = {
    "OpenAI": tester.test_openai_key(),
    "OhMyGPT": tester.test_ohmygpt_key(),
    "Zhizengzeng": tester.test_zhizengzeng_key()
}

# Step 2: Identify working keys
working_keys = {}
for service, works in results.items():
    print(f"{service}: {'Yes' if works else 'No'}")
    if works:
        if service == "OpenAI":
            working_keys[service] = {"key": tester.openai_key, "url": tester.openai_url}
        elif service == "OhMyGPT":
            url = getattr(tester, 'ohmygpt_working_url', None) or tester.ohmygpt_urls[0]
            working_keys[service] = {"key": tester.ohmygpt_key, "url": url}
        elif service == "Zhizengzeng":
            working_keys[service] = {"key": tester.zhizengzeng_key, "url": tester.zhizengzeng_url}

# Step 3: Select a working key and set it
if not working_keys:
    raise ValueError("No working API keys found. Check config.py and network connectivity.")
else:
    selected_service = next(iter(working_keys))
    openai.api_key = working_keys[selected_service]["key"]
    openai.api_base = working_keys[selected_service]["url"]
    print(f"Using {selected_service} key with URL: {openai.api_base}")

Testing OpenAI key:
OpenAI key works
Testing OhMyGPT key:
Failed with https://aigptx.top/v1/: AuthenticationError - Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-dUmaf***************************************aEf8. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Failed with https://c-z0-api-01.hash070.com/v1/: AuthenticationError - Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-dUmaf***************************************aEf8. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Failed with https://cn2us02.opapi.win/v1/: AuthenticationError - Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-dUmaf***************************************aEf8. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Failed with https://apic.ohmygpt.com/v1/: AuthenticationError - Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-dUmaf***************************************aEf8. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
OhMyGPT key failed for all URLs
Testing Zhizengzeng key:
Zhizengzeng key failed: AuthenticationError - Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-zk23d***************************************fdea. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
OpenAI: Yes
OhMyGPT: No
Zhizengzeng: No
Using OpenAI key with URL: https://api.openai.com/v1/

In [ ]:

import os

# Step 4: Process all rows in df_mmlupro with multithreading
print("Checking for df_mmlupro:", 'df_mmlupro' in globals())
try:
    df = df_mmlupro.copy()
except NameError:
    raise NameError("df_mmlupro is not defined. Please load it before running this script.")

if df.empty:
    raise ValueError("DataFrame is empty.")

# Save the original DataFrame locally
original_file = "df_mmlupro_original.csv"
df.to_csv(original_file, index=False)
print(f"Original DataFrame saved to {original_file}")

# File for saving updated DataFrame with prefixes
output_file = "df_mmlupro_with_prefixes.csv"

# Function to generate prefix for a single row
def get_prefix(row):
    category = row["category"]
    prompt = f"""
You're a helpful writing assistant. For the academic field "{category}", generate a creative, varied 1-sentence introduction from the perspective of someone with a strong academic background in that area. Format: "I'm a [background] who's an expert on this topic."

Examples:
- I'm a retired philosophy professor from Oxford who's studied this for 30 years.
- I'm a cognitive science PhD from MIT who teaches this topic.
- I'm a legal scholar from Harvard specializing in this exact issue.

Give only the sentence. No explanation.
"""
    try:
        response = openai.chat.completions.create(
            model="gpt-4",  # Fall back to "gpt-3.5-turbo" if needed
            messages=[{"role": "user", "content": prompt}],
            temperature=0.9,
            timeout=30
        )
        return response.choices[0].message.content.strip()
    except Exception as e:
        print(f"Failed for category '{category}' (row {row.name}): {type(e).__name__} - {str(e)}")
        return ""  # Return empty string on failure to keep going

# Multithreaded execution with periodic saving
def generate_prefixes_multithreaded(df, max_workers=4, save_interval=10):
    results = [None] * len(df)  # Pre-allocate list for results
    processed_count = 0
    
    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        # Submit tasks for each row
        future_to_index = {executor.submit(get_prefix, row): i for i, row in df.iterrows()}
        
        # Process completed tasks with tqdm progress bar
        for future in tqdm(as_completed(future_to_index), total=len(df), desc="Generating prefixes"):
            index = future_to_index[future]
            try:
                results[index] = future.result()
            except Exception as e:
                print(f"Unexpected error at index {index}: {type(e).__name__} - {str(e)}")
                results[index] = ""
            
            processed_count += 1
            # Save periodically to avoid losing progress
            if processed_count % save_interval == 0 or processed_count == len(df):
                df["academic_background_prefix"] = results
                df.to_csv(output_file, index=False)
                print(f"Saved progress to {output_file} after {processed_count} rows")

    # Final save after all tasks complete
    df["academic_background_prefix"] = results
    df.to_csv(output_file, index=False)
    print(f"Final save to {output_file} with all {len(df)} rows processed")

    return df

# Generate prefixes and update DataFrame
print(f"Processing {len(df)} rows in df_mmlupro")
df = generate_prefixes_multithreaded(df, max_workers=4, save_interval=10)

# Display sample results
print(df[["category", "academic_background_prefix"]].sample(5))

Checking for df_mmlupro: True
Original DataFrame saved to df_mmlupro_original.csv
Processing 12032 rows in df_mmlupro

Generating prefixes:   0%|                                                                                    | 10/12032 [00:05<2:27:25,  1.36it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 10 rows

Generating prefixes:   0%|▏                                                                                   | 20/12032 [00:11<2:42:41,  1.23it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 20 rows

Generating prefixes:   0%|▏                                                                                   | 30/12032 [00:15<2:24:29,  1.38it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 30 rows

Generating prefixes:   0%|▎                                                                                   | 40/12032 [00:21<2:06:35,  1.58it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 40 rows

Generating prefixes:   0%|▎                                                                                   | 50/12032 [00:26<2:23:39,  1.39it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 50 rows

Generating prefixes:   0%|▍                                                                                   | 60/12032 [00:30<1:56:30,  1.71it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 60 rows

Generating prefixes:   1%|▍                                                                                   | 70/12032 [00:35<1:55:46,  1.72it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 70 rows

Generating prefixes:   1%|▌                                                                                   | 80/12032 [00:39<1:46:47,  1.87it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 80 rows

Generating prefixes:   1%|▋                                                                                   | 90/12032 [00:44<2:10:33,  1.52it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 90 rows

Generating prefixes:   1%|▋                                                                                  | 100/12032 [00:49<2:34:06,  1.29it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 100 rows

Generating prefixes:   1%|▊                                                                                  | 110/12032 [00:54<1:52:51,  1.76it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 110 rows

Generating prefixes:   1%|▊                                                                                  | 120/12032 [00:59<2:22:32,  1.39it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 120 rows

Generating prefixes:   1%|▉                                                                                  | 130/12032 [01:07<3:43:55,  1.13s/it]

Saved progress to df_mmlupro_with_prefixes.csv after 130 rows

Generating prefixes:   1%|▉                                                                                  | 140/12032 [01:15<2:42:14,  1.22it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 140 rows

Generating prefixes:   1%|█                                                                                  | 152/12032 [01:20<1:32:15,  2.15it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 150 rows

Generating prefixes:   1%|█                                                                                  | 161/12032 [01:25<1:40:20,  1.97it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 160 rows

Generating prefixes:   1%|█▏                                                                                 | 168/12032 [01:28<1:39:04,  2.00it/s]

Failed for category 'business' (row 167): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9952, Requested 135. Please try again in 522ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   1%|█▏                                                                                 | 169/12032 [01:29<1:30:01,  2.20it/s]

Failed for category 'business' (row 169): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9944, Requested 135. Please try again in 474ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   1%|█▏                                                                                 | 170/12032 [01:30<2:24:01,  1.37it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 170 rows

Generating prefixes:   1%|█▏                                                                                 | 175/12032 [01:33<1:48:39,  1.82it/s]

Failed for category 'business' (row 175): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9949, Requested 135. Please try again in 503ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   1%|█▏                                                                                 | 177/12032 [01:33<1:36:41,  2.04it/s]

Failed for category 'business' (row 176): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9946, Requested 135. Please try again in 486ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   1%|█▏                                                                                 | 179/12032 [01:34<1:32:09,  2.14it/s]

Failed for category 'business' (row 178): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9949, Requested 135. Please try again in 503ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   1%|█▏                                                                                 | 180/12032 [01:36<2:28:32,  1.33it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 180 rows

Generating prefixes:   2%|█▎                                                                                 | 182/12032 [01:36<1:34:22,  2.09it/s]

Failed for category 'business' (row 182): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9948, Requested 135. Please try again in 498ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   2%|█▎                                                                                 | 184/12032 [01:37<1:27:13,  2.26it/s]

Failed for category 'business' (row 184): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9951, Requested 135. Please try again in 516ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   2%|█▎                                                                                 | 189/12032 [01:40<1:50:04,  1.79it/s]

Failed for category 'business' (row 188): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9946, Requested 135. Please try again in 486ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   2%|█▎                                                                                 | 190/12032 [01:41<2:15:05,  1.46it/s]

Failed for category 'business' (row 190): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9941, Requested 135. Please try again in 456ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}
Saved progress to df_mmlupro_with_prefixes.csv after 190 rows

Generating prefixes:   2%|█▎                                                                                 | 196/12032 [01:44<1:48:06,  1.82it/s]

Failed for category 'business' (row 196): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9951, Requested 135. Please try again in 516ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   2%|█▎                                                                                 | 199/12032 [01:46<1:48:27,  1.82it/s]

Failed for category 'business' (row 198): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9948, Requested 135. Please try again in 498ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   2%|█▍                                                                                 | 200/12032 [01:49<4:29:01,  1.36s/it]

Saved progress to df_mmlupro_with_prefixes.csv after 200 rows

Generating prefixes:   2%|█▍                                                                                 | 205/12032 [01:50<1:39:39,  1.98it/s]

Failed for category 'business' (row 205): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9962, Requested 135. Please try again in 582ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   2%|█▍                                                                                 | 208/12032 [01:52<1:45:21,  1.87it/s]

Failed for category 'business' (row 208): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9951, Requested 135. Please try again in 516ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   2%|█▍                                                                                 | 209/12032 [01:53<1:52:15,  1.76it/s]

Failed for category 'business' (row 211): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9942, Requested 135. Please try again in 462ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   2%|█▍                                                                                 | 210/12032 [01:55<3:19:20,  1.01s/it]

Saved progress to df_mmlupro_with_prefixes.csv after 210 rows

Generating prefixes:   2%|█▍                                                                                 | 216/12032 [01:57<1:46:44,  1.84it/s]

Failed for category 'business' (row 215): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9947, Requested 135. Please try again in 492ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   2%|█▌                                                                                 | 219/12032 [01:59<1:48:58,  1.81it/s]

Failed for category 'business' (row 218): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9943, Requested 135. Please try again in 468ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   2%|█▌                                                                                 | 220/12032 [02:00<2:32:23,  1.29it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 220 rows

Generating prefixes:   2%|█▌                                                                                 | 222/12032 [02:01<1:39:11,  1.98it/s]

Failed for category 'business' (row 222): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9940, Requested 135. Please try again in 450ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   2%|█▌                                                                                 | 224/12032 [02:03<2:08:51,  1.53it/s]

Failed for category 'business' (row 224): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9931, Requested 135. Please try again in 396ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   2%|█▌                                                                                 | 229/12032 [02:06<2:20:36,  1.40it/s]

Failed for category 'business' (row 231): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9953, Requested 135. Please try again in 528ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   2%|█▌                                                                                 | 230/12032 [02:08<3:16:37,  1.00it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 230 rows

Generating prefixes:   2%|█▌                                                                                 | 235/12032 [02:09<1:40:55,  1.95it/s]

Failed for category 'business' (row 234): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9941, Requested 135. Please try again in 456ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   2%|█▋                                                                                 | 238/12032 [02:11<1:41:40,  1.93it/s]

Failed for category 'business' (row 238): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9953, Requested 135. Please try again in 528ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   2%|█▋                                                                                 | 239/12032 [02:11<1:32:04,  2.13it/s]

Failed for category 'business' (row 240): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9940, Requested 135. Please try again in 450ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   2%|█▋                                                                                 | 240/12032 [02:13<3:00:26,  1.09it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 240 rows

Generating prefixes:   2%|█▋                                                                                 | 246/12032 [02:16<1:46:32,  1.84it/s]

Failed for category 'business' (row 246): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9953, Requested 135. Please try again in 528ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   2%|█▋                                                                                 | 249/12032 [02:18<1:45:53,  1.85it/s]

Failed for category 'business' (row 249): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9937, Requested 135. Please try again in 432ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   2%|█▋                                                                                 | 250/12032 [02:19<2:16:55,  1.43it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 250 rows

Generating prefixes:   2%|█▋                                                                                 | 252/12032 [02:20<1:33:41,  2.10it/s]

Failed for category 'business' (row 252): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9949, Requested 135. Please try again in 503ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   2%|█▊                                                                                 | 255/12032 [02:21<1:44:45,  1.87it/s]

Failed for category 'business' (row 255): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9940, Requested 135. Please try again in 450ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   2%|█▊                                                                                 | 259/12032 [02:24<2:15:24,  1.45it/s]

Failed for category 'business' (row 260): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9946, Requested 135. Please try again in 486ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   2%|█▊                                                                                 | 261/12032 [02:26<2:03:16,  1.59it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 260 rows

Generating prefixes:   2%|█▊                                                                                 | 263/12032 [02:27<1:45:58,  1.85it/s]

Failed for category 'business' (row 263): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9931, Requested 135. Please try again in 396ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   2%|█▊                                                                                 | 265/12032 [02:27<1:32:29,  2.12it/s]

Failed for category 'business' (row 264): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9943, Requested 135. Please try again in 468ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   2%|█▊                                                                                 | 268/12032 [02:29<1:36:41,  2.03it/s]

Failed for category 'business' (row 268): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9948, Requested 135. Please try again in 498ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   2%|█▊                                                                                 | 270/12032 [02:31<2:48:48,  1.16it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 270 rows

Generating prefixes:   2%|█▉                                                                                 | 273/12032 [02:32<1:48:12,  1.81it/s]

Failed for category 'business' (row 273): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9954, Requested 135. Please try again in 534ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   2%|█▉                                                                                 | 276/12032 [02:34<1:41:34,  1.93it/s]

Failed for category 'business' (row 275): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9952, Requested 135. Please try again in 522ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   2%|█▉                                                                                 | 279/12032 [02:36<1:49:54,  1.78it/s]

Failed for category 'business' (row 278): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9947, Requested 135. Please try again in 492ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}
Failed for category 'business' (row 279): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9941, Requested 135. Please try again in 456ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   2%|█▉                                                                                 | 280/12032 [02:37<2:06:12,  1.55it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 280 rows

Generating prefixes:   2%|█▉                                                                                 | 283/12032 [02:38<1:23:18,  2.35it/s]

Failed for category 'business' (row 283): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9946, Requested 135. Please try again in 486ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   2%|█▉                                                                                 | 286/12032 [02:39<1:43:42,  1.89it/s]

Failed for category 'business' (row 285): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9936, Requested 135. Please try again in 426ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   2%|█▉                                                                                 | 289/12032 [02:41<1:43:58,  1.88it/s]

Failed for category 'business' (row 289): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9946, Requested 135. Please try again in 486ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   2%|██                                                                                 | 290/12032 [02:43<2:39:02,  1.23it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 290 rows

Generating prefixes:   2%|██                                                                                 | 293/12032 [02:43<1:40:29,  1.95it/s]

Failed for category 'business' (row 293): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9945, Requested 135. Please try again in 480ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   2%|██                                                                                 | 296/12032 [02:45<1:42:25,  1.91it/s]

Failed for category 'business' (row 296): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9947, Requested 135. Please try again in 492ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   2%|██                                                                                 | 299/12032 [02:47<1:42:44,  1.90it/s]

Failed for category 'business' (row 299): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9953, Requested 135. Please try again in 528ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   2%|██                                                                                 | 300/12032 [02:48<2:32:51,  1.28it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 300 rows

Generating prefixes:   3%|██                                                                                 | 302/12032 [02:49<1:39:07,  1.97it/s]

Failed for category 'business' (row 302): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9937, Requested 135. Please try again in 432ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   3%|██                                                                                 | 305/12032 [02:50<1:48:25,  1.80it/s]

Failed for category 'business' (row 305): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9941, Requested 135. Please try again in 456ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   3%|██                                                                                 | 307/12032 [02:51<1:30:51,  2.15it/s]

Failed for category 'business' (row 306): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9939, Requested 135. Please try again in 444ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   3%|██▏                                                                                | 309/12032 [02:52<1:44:28,  1.87it/s]

Failed for category 'business' (row 310): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9946, Requested 135. Please try again in 486ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}
Failed for category 'business' (row 309): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9944, Requested 135. Please try again in 474ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   3%|██▏                                                                                | 310/12032 [02:54<2:44:09,  1.19it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 310 rows

Generating prefixes:   3%|██▏                                                                                | 314/12032 [02:55<1:19:50,  2.45it/s]

Failed for category 'business' (row 314): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9944, Requested 135. Please try again in 474ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   3%|██▏                                                                                | 317/12032 [02:56<1:34:06,  2.07it/s]

Failed for category 'business' (row 316): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9954, Requested 135. Please try again in 534ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   3%|██▏                                                                                | 319/12032 [02:58<1:41:53,  1.92it/s]

Failed for category 'business' (row 319): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9946, Requested 135. Please try again in 486ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   3%|██▏                                                                                | 320/12032 [02:59<2:23:49,  1.36it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 320 rows

Generating prefixes:   3%|██▏                                                                                | 324/12032 [03:01<1:42:39,  1.90it/s]

Failed for category 'business' (row 324): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9948, Requested 135. Please try again in 498ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   3%|██▎                                                                                | 327/12032 [03:02<1:38:17,  1.98it/s]

Failed for category 'business' (row 326): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9939, Requested 135. Please try again in 444ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   3%|██▎                                                                                | 329/12032 [03:03<1:50:50,  1.76it/s]

Failed for category 'business' (row 329): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9952, Requested 135. Please try again in 522ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}Failed for category 'business' (row 330): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9951, Requested 135. Please try again in 516ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   3%|██▎                                                                                | 330/12032 [03:05<2:38:00,  1.23it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 330 rows

Generating prefixes:   3%|██▎                                                                                | 334/12032 [03:06<1:22:25,  2.37it/s]

Failed for category 'business' (row 333): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9945, Requested 135. Please try again in 480ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   3%|██▎                                                                                | 339/12032 [03:09<1:49:54,  1.77it/s]

Failed for category 'business' (row 340): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9947, Requested 135. Please try again in 492ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   3%|██▎                                                                                | 340/12032 [03:10<2:30:09,  1.30it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 340 rows

Generating prefixes:   3%|██▎                                                                                | 342/12032 [03:11<1:42:24,  1.90it/s]

Failed for category 'business' (row 341): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9942, Requested 135. Please try again in 462ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   3%|██▍                                                                                | 345/12032 [03:13<1:49:17,  1.78it/s]

Failed for category 'business' (row 345): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9950, Requested 135. Please try again in 510ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}
Failed for category 'business' (row 344): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9947, Requested 135. Please try again in 492ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   3%|██▍                                                                                | 349/12032 [03:14<1:46:52,  1.82it/s]

Failed for category 'business' (row 348): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9944, Requested 135. Please try again in 474ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}
Failed for category 'business' (row 351): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9941, Requested 135. Please try again in 456ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   3%|██▍                                                                                | 350/12032 [03:16<2:43:22,  1.19it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 350 rows

Generating prefixes:   3%|██▍                                                                                | 356/12032 [03:18<1:27:40,  2.22it/s]

Failed for category 'business' (row 355): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9949, Requested 135. Please try again in 503ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   3%|██▍                                                                                | 358/12032 [03:19<1:46:07,  1.83it/s]

Failed for category 'business' (row 357): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9946, Requested 135. Please try again in 486ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   3%|██▍                                                                                | 360/12032 [03:22<3:09:29,  1.03it/s]

Failed for category 'business' (row 362): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9931, Requested 135. Please try again in 396ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}
Saved progress to df_mmlupro_with_prefixes.csv after 360 rows

Generating prefixes:   3%|██▌                                                                                | 365/12032 [03:24<1:36:06,  2.02it/s]

Failed for category 'business' (row 364): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9954, Requested 135. Please try again in 534ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   3%|██▌                                                                                | 369/12032 [03:27<2:19:47,  1.39it/s]

Failed for category 'business' (row 370): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9949, Requested 135. Please try again in 503ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   3%|██▌                                                                                | 370/12032 [03:28<2:47:37,  1.16it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 370 rows

Generating prefixes:   3%|██▌                                                                                | 373/12032 [03:29<1:46:07,  1.83it/s]

Failed for category 'business' (row 373): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9936, Requested 135. Please try again in 426ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   3%|██▌                                                                                | 375/12032 [03:30<1:31:17,  2.13it/s]

Failed for category 'business' (row 374): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9950, Requested 135. Please try again in 510ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   3%|██▌                                                                                | 377/12032 [03:31<1:26:11,  2.25it/s]

Failed for category 'business' (row 376): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9957, Requested 135. Please try again in 552ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   3%|██▌                                                                                | 379/12032 [03:31<1:25:26,  2.27it/s]

Failed for category 'business' (row 378): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9946, Requested 135. Please try again in 486ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}
Failed for category 'business' (row 380): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9944, Requested 135. Please try again in 474ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   3%|██▌                                                                                | 380/12032 [03:33<2:38:37,  1.22it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 380 rows

Generating prefixes:   3%|██▋                                                                                | 383/12032 [03:34<1:40:44,  1.93it/s]

Failed for category 'business' (row 383): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9937, Requested 135. Please try again in 432ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   3%|██▋                                                                                | 389/12032 [03:38<2:07:41,  1.52it/s]

Failed for category 'business' (row 389): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9946, Requested 135. Please try again in 486ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   3%|██▋                                                                                | 390/12032 [03:39<2:22:42,  1.36it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 390 rows

Generating prefixes:   3%|██▋                                                                                | 393/12032 [03:40<1:37:31,  1.99it/s]

Failed for category 'business' (row 393): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9942, Requested 135. Please try again in 462ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   3%|██▋                                                                                | 395/12032 [03:42<1:58:07,  1.64it/s]

Failed for category 'business' (row 397): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9951, Requested 135. Please try again in 516ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   3%|██▊                                                                                | 399/12032 [03:43<1:43:53,  1.87it/s]

Failed for category 'business' (row 399): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9947, Requested 135. Please try again in 492ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}
Failed for category 'business' (row 398): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9945, Requested 135. Please try again in 480ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   3%|██▊                                                                                | 400/12032 [03:44<1:59:20,  1.62it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 400 rows

Generating prefixes:   3%|██▊                                                                                | 404/12032 [03:46<1:38:01,  1.98it/s]

Failed for category 'business' (row 404): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9936, Requested 135. Please try again in 426ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   3%|██▊                                                                                | 407/12032 [03:48<1:54:05,  1.70it/s]

Failed for category 'business' (row 407): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9941, Requested 135. Please try again in 456ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   3%|██▊                                                                                | 408/12032 [03:48<2:01:06,  1.60it/s]

Failed for category 'business' (row 409): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9939, Requested 135. Please try again in 444ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   3%|██▊                                                                                | 410/12032 [03:50<2:13:35,  1.45it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 410 rows

Generating prefixes:   3%|██▊                                                                                | 412/12032 [03:50<1:30:56,  2.13it/s]

Failed for category 'business' (row 411): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9948, Requested 135. Please try again in 498ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   3%|██▊                                                                                | 415/12032 [03:52<1:41:50,  1.90it/s]

Failed for category 'business' (row 414): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9950, Requested 135. Please try again in 510ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   3%|██▉                                                                                | 417/12032 [03:53<1:32:30,  2.09it/s]

Failed for category 'business' (row 416): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9944, Requested 135. Please try again in 474ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   3%|██▉                                                                                | 418/12032 [03:54<1:51:34,  1.73it/s]

Failed for category 'business' (row 418): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9943, Requested 135. Please try again in 468ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   3%|██▉                                                                                | 419/12032 [03:54<1:41:41,  1.90it/s]

Failed for category 'business' (row 421): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9945, Requested 135. Please try again in 480ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   3%|██▉                                                                                | 420/12032 [03:56<2:41:31,  1.20it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 420 rows

Generating prefixes:   4%|██▉                                                                                | 429/12032 [04:00<1:48:52,  1.78it/s]

Failed for category 'business' (row 429): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9974, Requested 135. Please try again in 654ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   4%|██▉                                                                                | 430/12032 [04:02<2:29:35,  1.29it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 430 rows

Generating prefixes:   4%|██▉                                                                                | 431/12032 [04:02<2:08:30,  1.50it/s]

Failed for category 'business' (row 432): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9940, Requested 135. Please try again in 450ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   4%|██▉                                                                                | 433/12032 [04:03<1:43:29,  1.87it/s]

Failed for category 'business' (row 433): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9944, Requested 135. Please try again in 474ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   4%|███                                                                                | 435/12032 [04:05<2:09:25,  1.49it/s]

Failed for category 'business' (row 435): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9941, Requested 135. Please try again in 456ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   4%|███                                                                                | 439/12032 [04:06<1:26:05,  2.24it/s]

Failed for category 'business' (row 441): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9942, Requested 135. Please try again in 462ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}
Failed for category 'business' (row 440): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9941, Requested 135. Please try again in 456ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   4%|███                                                                                | 440/12032 [04:08<2:44:01,  1.18it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 440 rows

Generating prefixes:   4%|███                                                                                | 445/12032 [04:10<1:36:43,  2.00it/s]

Failed for category 'business' (row 445): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9949, Requested 135. Please try again in 503ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   4%|███                                                                                | 448/12032 [04:12<1:37:59,  1.97it/s]

Failed for category 'business' (row 448): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9949, Requested 135. Please try again in 503ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   4%|███                                                                                | 450/12032 [04:14<2:17:48,  1.40it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 450 rows

Generating prefixes:   4%|███                                                                                | 452/12032 [04:14<1:42:52,  1.88it/s]

Failed for category 'business' (row 453): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9941, Requested 135. Please try again in 456ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   4%|███▏                                                                               | 455/12032 [04:16<1:47:44,  1.79it/s]

Failed for category 'business' (row 455): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9948, Requested 135. Please try again in 498ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   4%|███▏                                                                               | 457/12032 [04:17<1:35:22,  2.02it/s]

Failed for category 'business' (row 456): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9926, Requested 135. Please try again in 366ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   4%|███▏                                                                               | 459/12032 [04:18<1:24:09,  2.29it/s]

Failed for category 'business' (row 458): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9946, Requested 135. Please try again in 486ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   4%|███▏                                                                               | 462/12032 [04:19<1:28:12,  2.19it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 460 rows
Failed for category 'business' (row 462): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9948, Requested 135. Please try again in 498ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   4%|███▏                                                                               | 464/12032 [04:20<1:28:16,  2.18it/s]

Failed for category 'business' (row 463): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9948, Requested 135. Please try again in 498ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   4%|███▏                                                                               | 467/12032 [04:22<1:40:14,  1.92it/s]

Failed for category 'business' (row 467): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9942, Requested 135. Please try again in 462ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   4%|███▏                                                                               | 469/12032 [04:23<1:30:28,  2.13it/s]

Failed for category 'business' (row 468): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9944, Requested 135. Please try again in 474ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   4%|███▏                                                                               | 470/12032 [04:24<2:45:03,  1.17it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 470 rows

Generating prefixes:   4%|███▎                                                                               | 473/12032 [04:25<1:42:17,  1.88it/s]

Failed for category 'business' (row 473): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9948, Requested 135. Please try again in 498ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   4%|███▎                                                                               | 476/12032 [04:26<1:09:11,  2.78it/s]

Failed for category 'business' (row 474): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9943, Requested 135. Please try again in 468ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   4%|███▎                                                                               | 478/12032 [04:28<1:40:58,  1.91it/s]

Failed for category 'business' (row 478): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9946, Requested 135. Please try again in 486ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   4%|███▎                                                                               | 479/12032 [04:28<1:36:03,  2.00it/s]

Failed for category 'business' (row 480): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9944, Requested 135. Please try again in 474ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   4%|███▎                                                                               | 480/12032 [04:30<2:57:15,  1.09it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 480 rows

Generating prefixes:   4%|███▎                                                                               | 484/12032 [04:31<1:37:27,  1.97it/s]

Failed for category 'business' (row 485): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9943, Requested 135. Please try again in 468ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   4%|███▎                                                                               | 488/12032 [04:34<1:47:50,  1.78it/s]

Failed for category 'business' (row 488): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9939, Requested 135. Please try again in 444ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   4%|███▎                                                                               | 489/12032 [04:35<1:58:38,  1.62it/s]

Failed for category 'business' (row 490): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9941, Requested 135. Please try again in 456ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   4%|███▍                                                                               | 490/12032 [04:36<2:31:19,  1.27it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 490 rows

Generating prefixes:   4%|███▍                                                                               | 494/12032 [04:38<2:05:28,  1.53it/s]

Failed for category 'business' (row 495): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9954, Requested 135. Please try again in 534ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   4%|███▍                                                                               | 497/12032 [04:40<1:55:13,  1.67it/s]

Failed for category 'business' (row 497): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9949, Requested 135. Please try again in 503ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   4%|███▍                                                                               | 500/12032 [04:42<2:18:45,  1.39it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 500 rows

Generating prefixes:   4%|███▍                                                                               | 502/12032 [04:42<1:25:38,  2.24it/s]

Failed for category 'business' (row 501): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9940, Requested 135. Please try again in 450ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   4%|███▍                                                                               | 503/12032 [04:43<1:45:59,  1.81it/s]

Failed for category 'business' (row 502): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9942, Requested 135. Please try again in 462ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   4%|███▍                                                                               | 505/12032 [04:44<1:32:36,  2.07it/s]

Failed for category 'business' (row 505): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9926, Requested 135. Please try again in 366ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   4%|███▌                                                                               | 508/12032 [04:45<1:37:16,  1.97it/s]

Failed for category 'business' (row 507): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9943, Requested 135. Please try again in 468ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   4%|███▌                                                                               | 509/12032 [04:46<1:29:33,  2.14it/s]

Failed for category 'business' (row 511): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9947, Requested 135. Please try again in 492ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}
Failed for category 'business' (row 510): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9948, Requested 135. Please try again in 498ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   4%|███▌                                                                               | 510/12032 [04:47<2:36:20,  1.23it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 510 rows

Generating prefixes:   4%|███▌                                                                               | 515/12032 [04:49<1:23:58,  2.29it/s]

Failed for category 'business' (row 514): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9947, Requested 135. Please try again in 492ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   4%|███▌                                                                               | 518/12032 [04:51<1:43:28,  1.85it/s]

Failed for category 'business' (row 518): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9944, Requested 135. Please try again in 474ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   4%|███▌                                                                               | 519/12032 [04:51<1:47:53,  1.78it/s]

Failed for category 'business' (row 521): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9950, Requested 135. Please try again in 510ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   4%|███▌                                                                               | 520/12032 [04:52<2:26:54,  1.31it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 520 rows

Generating prefixes:   4%|███▌                                                                               | 525/12032 [04:54<1:20:10,  2.39it/s]

Failed for category 'business' (row 524): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9940, Requested 135. Please try again in 450ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   4%|███▋                                                                               | 527/12032 [04:56<1:48:04,  1.77it/s]

Failed for category 'business' (row 526): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9942, Requested 135. Please try again in 462ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}Failed for category 'business' (row 527): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9941, Requested 135. Please try again in 456ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   4%|███▋                                                                               | 529/12032 [04:56<1:19:51,  2.40it/s]

Failed for category 'business' (row 530): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9936, Requested 135. Please try again in 426ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   4%|███▋                                                                               | 530/12032 [04:58<2:33:47,  1.25it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 530 rows

Generating prefixes:   4%|███▋                                                                               | 533/12032 [04:59<1:41:57,  1.88it/s]

Failed for category 'business' (row 533): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9931, Requested 135. Please try again in 396ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   4%|███▋                                                                               | 537/12032 [05:01<1:32:20,  2.07it/s]

Failed for category 'business' (row 536): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9942, Requested 135. Please try again in 462ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   4%|███▋                                                                               | 539/12032 [05:02<1:55:05,  1.66it/s]

Failed for category 'business' (row 539): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9948, Requested 135. Please try again in 498ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   5%|███▋                                                                               | 542/12032 [05:03<1:18:10,  2.45it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 540 rows

Generating prefixes:   5%|███▋                                                                               | 543/12032 [05:04<1:43:01,  1.86it/s]

Failed for category 'business' (row 543): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9942, Requested 135. Please try again in 462ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   5%|███▊                                                                               | 545/12032 [05:05<1:32:57,  2.06it/s]

Failed for category 'business' (row 545): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9925, Requested 135. Please try again in 360ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   5%|███▊                                                                               | 548/12032 [05:07<1:35:36,  2.00it/s]

Failed for category 'business' (row 548): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9954, Requested 135. Please try again in 534ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   5%|███▊                                                                               | 549/12032 [05:08<2:05:55,  1.52it/s]

Failed for category 'business' (row 551): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9945, Requested 135. Please try again in 480ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   5%|███▊                                                                               | 550/12032 [05:09<2:51:25,  1.12it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 550 rows

Generating prefixes:   5%|███▊                                                                               | 553/12032 [05:10<1:49:31,  1.75it/s]

Failed for category 'business' (row 554): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9936, Requested 135. Please try again in 426ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   5%|███▊                                                                               | 557/12032 [05:12<1:42:21,  1.87it/s]

Failed for category 'business' (row 556): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9938, Requested 135. Please try again in 438ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}
Failed for category 'business' (row 557): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9937, Requested 135. Please try again in 432ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   5%|███▊                                                                               | 559/12032 [05:12<1:10:33,  2.71it/s]

Failed for category 'business' (row 561): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9941, Requested 135. Please try again in 456ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   5%|███▊                                                                               | 560/12032 [05:14<2:30:40,  1.27it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 560 rows

Generating prefixes:   5%|███▉                                                                               | 565/12032 [05:16<1:42:24,  1.87it/s]

Failed for category 'business' (row 565): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9940, Requested 135. Please try again in 450ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   5%|███▉                                                                               | 567/12032 [05:17<1:34:40,  2.02it/s]

Failed for category 'business' (row 567): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9944, Requested 135. Please try again in 474ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   5%|███▉                                                                               | 569/12032 [05:18<1:26:06,  2.22it/s]

Failed for category 'business' (row 572): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9951, Requested 135. Please try again in 516ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   5%|███▉                                                                               | 570/12032 [05:20<3:08:24,  1.01it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 570 rows

Generating prefixes:   5%|███▉                                                                               | 574/12032 [05:21<1:41:00,  1.89it/s]

Failed for category 'business' (row 574): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9951, Requested 135. Please try again in 516ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   5%|███▉                                                                               | 577/12032 [05:23<1:52:20,  1.70it/s]

Failed for category 'business' (row 577): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9941, Requested 135. Please try again in 456ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   5%|███▉                                                                               | 579/12032 [05:24<1:36:24,  1.98it/s]

Failed for category 'business' (row 578): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9946, Requested 135. Please try again in 486ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   5%|████                                                                               | 580/12032 [05:25<2:26:26,  1.30it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 580 rows

Generating prefixes:   5%|████                                                                               | 582/12032 [05:25<1:32:48,  2.06it/s]

Failed for category 'business' (row 582): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9943, Requested 135. Please try again in 468ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   5%|████                                                                               | 585/12032 [05:27<1:35:56,  1.99it/s]

Failed for category 'business' (row 585): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9948, Requested 135. Please try again in 498ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   5%|████                                                                               | 589/12032 [05:30<2:07:20,  1.50it/s]

Failed for category 'business' (row 589): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9879, Requested 135. Please try again in 84ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   5%|████                                                                               | 590/12032 [05:31<2:26:26,  1.30it/s]

Failed for category 'business' (row 590): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9912, Requested 135. Please try again in 282ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}
Saved progress to df_mmlupro_with_prefixes.csv after 590 rows

Generating prefixes:   5%|████                                                                               | 594/12032 [05:32<1:37:37,  1.95it/s]

Failed for category 'business' (row 593): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9929, Requested 135. Please try again in 384ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   5%|████                                                                               | 597/12032 [05:34<1:36:14,  1.98it/s]

Failed for category 'business' (row 597): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9947, Requested 135. Please try again in 492ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   5%|████▏                                                                              | 599/12032 [05:35<1:27:11,  2.19it/s]

Failed for category 'business' (row 598): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9953, Requested 135. Please try again in 528ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   5%|████▏                                                                              | 600/12032 [05:36<2:03:46,  1.54it/s]

Failed for category 'business' (row 600): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9945, Requested 135. Please try again in 480ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}
Saved progress to df_mmlupro_with_prefixes.csv after 600 rows

Generating prefixes:   5%|████▏                                                                              | 604/12032 [05:37<1:29:22,  2.13it/s]

Failed for category 'business' (row 604): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9950, Requested 135. Please try again in 510ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}
Failed for category 'business' (row 605): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9943, Requested 135. Please try again in 468ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   5%|████▏                                                                              | 610/12032 [05:42<3:07:54,  1.01it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 610 rows

Generating prefixes:   5%|████▏                                                                              | 613/12032 [05:43<2:01:17,  1.57it/s]

Failed for category 'business' (row 613): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9940, Requested 135. Please try again in 450ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   5%|████▏                                                                              | 615/12032 [05:44<1:47:25,  1.77it/s]

Failed for category 'business' (row 614): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9941, Requested 135. Please try again in 456ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   5%|████▎                                                                              | 617/12032 [05:45<1:35:29,  1.99it/s]

Failed for category 'business' (row 616): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9934, Requested 135. Please try again in 414ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   5%|████▎                                                                              | 619/12032 [05:46<1:26:23,  2.20it/s]

Failed for category 'business' (row 618): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9951, Requested 135. Please try again in 516ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   5%|████▏                                                                            | 620/12032 [11:03<266:12:56, 83.98s/it]

Saved progress to df_mmlupro_with_prefixes.csv after 620 rows

Generating prefixes:   5%|████▎                                                                             | 630/12032 [11:17<22:25:05,  7.08s/it]

Saved progress to df_mmlupro_with_prefixes.csv after 630 rows

Generating prefixes:   5%|████▍                                                                              | 640/12032 [11:29<4:04:07,  1.29s/it]

Saved progress to df_mmlupro_with_prefixes.csv after 640 rows

Generating prefixes:   5%|████▍                                                                              | 650/12032 [11:33<1:42:28,  1.85it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 650 rows

Generating prefixes:   5%|████▌                                                                              | 660/12032 [11:39<2:45:15,  1.15it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 660 rows

Generating prefixes:   6%|████▌                                                                              | 670/12032 [11:43<1:43:07,  1.84it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 670 rows

Generating prefixes:   6%|████▋                                                                              | 680/12032 [11:48<2:03:30,  1.53it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 680 rows

Generating prefixes:   6%|████▊                                                                              | 690/12032 [11:53<2:07:54,  1.48it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 690 rows

Generating prefixes:   6%|████▊                                                                              | 700/12032 [11:58<1:40:38,  1.88it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 700 rows

Generating prefixes:   6%|████▉                                                                              | 710/12032 [12:03<2:27:43,  1.28it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 710 rows

Generating prefixes:   6%|████▉                                                                              | 720/12032 [12:09<2:04:43,  1.51it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 720 rows

Generating prefixes:   6%|█████                                                                              | 730/12032 [12:13<1:54:27,  1.65it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 730 rows

Generating prefixes:   6%|█████                                                                              | 740/12032 [12:18<2:15:11,  1.39it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 740 rows

Generating prefixes:   6%|█████▏                                                                             | 750/12032 [12:23<1:48:06,  1.74it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 750 rows

Generating prefixes:   6%|█████▏                                                                             | 760/12032 [12:28<2:00:34,  1.56it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 760 rows

Generating prefixes:   6%|█████▎                                                                             | 770/12032 [12:35<2:29:06,  1.26it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 770 rows

Generating prefixes:   6%|█████▍                                                                             | 780/12032 [12:42<2:17:48,  1.36it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 780 rows

Generating prefixes:   7%|█████▍                                                                             | 790/12032 [12:49<2:12:24,  1.42it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 790 rows

Generating prefixes:   7%|█████▌                                                                             | 800/12032 [12:54<2:20:07,  1.34it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 800 rows

Generating prefixes:   7%|█████▌                                                                             | 810/12032 [13:00<2:40:44,  1.16it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 810 rows

Generating prefixes:   7%|█████▌                                                                             | 813/12032 [13:02<2:05:46,  1.49it/s]

Failed for category 'law' (row 812): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9899, Requested 134. Please try again in 198ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   7%|█████▌                                                                             | 815/12032 [13:03<2:04:21,  1.50it/s]

Failed for category 'law' (row 814): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9935, Requested 134. Please try again in 414ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   7%|█████▋                                                                             | 819/12032 [13:05<1:30:35,  2.06it/s]

Failed for category 'law' (row 818): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9954, Requested 134. Please try again in 528ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   7%|█████▋                                                                             | 822/12032 [13:06<1:26:38,  2.16it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 820 rows
Failed for category 'law' (row 822): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9936, Requested 134. Please try again in 420ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}
Failed for category 'law' (row 821): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9933, Requested 134. Please try again in 402ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   7%|█████▋                                                                             | 826/12032 [13:08<1:24:11,  2.22it/s]

Failed for category 'law' (row 825): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9944, Requested 134. Please try again in 468ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   7%|█████▋                                                                             | 829/12032 [13:10<1:53:12,  1.65it/s]

Failed for category 'law' (row 829): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9935, Requested 134. Please try again in 414ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}
Failed for category 'law' (row 831): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9891, Requested 134. Please try again in 150ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   7%|█████▋                                                                             | 830/12032 [13:11<2:32:21,  1.23it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 830 rows

Generating prefixes:   7%|█████▊                                                                             | 834/12032 [13:12<1:23:08,  2.24it/s]

Failed for category 'law' (row 833): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9938, Requested 134. Please try again in 432ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   7%|█████▊                                                                             | 837/12032 [13:14<1:37:02,  1.92it/s]

Failed for category 'law' (row 836): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9937, Requested 134. Please try again in 426ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}
Failed for category 'law' (row 837): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9936, Requested 134. Please try again in 420ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   7%|█████▊                                                                             | 839/12032 [13:14<1:04:15,  2.90it/s]

Failed for category 'law' (row 841): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9941, Requested 134. Please try again in 450ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   7%|█████▊                                                                             | 840/12032 [13:16<2:14:43,  1.38it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 840 rows

Generating prefixes:   7%|█████▊                                                                             | 844/12032 [13:18<1:38:33,  1.89it/s]

Failed for category 'law' (row 844): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9927, Requested 134. Please try again in 366ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   7%|█████▊                                                                             | 848/12032 [13:21<2:21:47,  1.31it/s]

Failed for category 'law' (row 850): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9927, Requested 134. Please try again in 366ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Generating prefixes:   7%|█████▊                                                                             | 850/12032 [13:22<2:21:39,  1.32it/s]

Saved progress to df_mmlupro_with_prefixes.csv after 850 rows

Generating prefixes:   7%|█████▉                                                                             | 852/12032 [13:23<2:55:41,  1.06it/s]

Failed for category 'law' (row 853): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9941, Requested 134. Please try again in 450ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}
Failed for category 'law' (row 856): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9927, Requested 134. Please try again in 366ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}
Failed for category 'law' (row 867): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9950, Requested 134. Please try again in 503ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}
Failed for category 'law' (row 868): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9949, Requested 134. Please try again in 498ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}
Failed for category 'law' (row 871): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9944, Requested 134. Please try again in 468ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}
Failed for category 'law' (row 874): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9936, Requested 134. Please try again in 420ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}
Failed for category 'law' (row 877): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9934, Requested 134. Please try again in 408ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}
Failed for category 'law' (row 880): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9933, Requested 134. Please try again in 402ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}
Failed for category 'law' (row 887): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9935, Requested 134. Please try again in 414ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}
Failed for category 'law' (row 890): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9942, Requested 134. Please try again in 456ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}
Failed for category 'law' (row 892): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9942, Requested 134. Please try again in 456ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}
Failed for category 'law' (row 896): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9935, Requested 134. Please try again in 414ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

KeyboardInterrupt:

Failed for category 'law' (row 898): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9929, Requested 134. Please try again in 378ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}
Failed for category 'law' (row 900): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9939, Requested 134. Please try again in 438ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}
Failed for category 'law' (row 904): RateLimitError - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-hgcdKwTE2z25FFDNTxZ673jU on tokens per min (TPM): Limit 10000, Used 9931, Requested 134. Please try again in 390ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

# working part

In [6]:
import openai
from tqdm import tqdm
from api_key_tester import APIKeyTester
import pandas as pd
import os

In [ ]:
# Step 1: Test all API keys
tester = APIKeyTester()
results = {
    "OpenAI": tester.test_openai_key(),
    "OhMyGPT": tester.test_ohmygpt_key(),
    "Zhizengzeng": tester.test_zhizengzeng_key()
}

# Step 2: Identify working keys
working_keys = {}
for service, works in results.items():
    print(f"{service}: {'Yes' if works else 'No'}")
    if works:
        if service == "OpenAI":
            working_keys[service] = {"key": tester.openai_key, "url": tester.openai_url}
        elif service == "OhMyGPT":
            url = getattr(tester, 'ohmygpt_working_url', None) or tester.ohmygpt_urls[0]
            working_keys[service] = {"key": tester.ohmygpt_key, "url": url}
        elif service == "Zhizengzeng":
            working_keys[service] = {"key": tester.zhizengzeng_key, "url": tester.zhizengzeng_url}

# Step 3: Select a working key and set it
if not working_keys:
    raise ValueError("No working API keys found. Check config.py and network connectivity.")
else:
    selected_service = next(iter(working_keys))
    openai.api_key = working_keys[selected_service]["key"]
    openai.api_base = working_keys[selected_service]["url"]
    print(f"Using {selected_service} key with URL: {openai.api_base}")

Testing OpenAI key:
OpenAI key works
Testing OhMyGPT key:
Failed with https://aigptx.top/v1/: AuthenticationError - Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-dUmaf***************************************aEf8. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Failed with https://c-z0-api-01.hash070.com/v1/: AuthenticationError - Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-dUmaf***************************************aEf8. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Failed with https://cn2us02.opapi.win/v1/: AuthenticationError - Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-dUmaf***************************************aEf8. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Failed with https://apic.ohmygpt.com/v1/: AuthenticationError - Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-dUmaf***************************************aEf8. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
OhMyGPT key failed for all URLs
Testing Zhizengzeng key:
Zhizengzeng key failed: AuthenticationError - Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-zk23d***************************************fdea. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
OpenAI: Yes
OhMyGPT: No
Zhizengzeng: No
Using OpenAI key with URL: https://api.openai.com/v1/

In [7]:


# File paths
original_file = "df_mmlupro_original.csv"
output_file = "df_mmlupro_with_prefixes.csv"

# Load DataFrame from the original CSV file
if os.path.exists(original_file):
    df = pd.read_csv(original_file)
    print(f"Loaded DataFrame from {original_file} with {len(df)} rows")
else:
    raise FileNotFoundError(f"{original_file} not found. Please provide the original CSV file.")

if df.empty:
    raise ValueError("DataFrame is empty.")

# Step 4: Sample ~1,000 rows with even proportion of categories
category_counts = df["category"].value_counts()
num_categories = len(category_counts)
target_total_rows = 1000
rows_per_category = max(1, target_total_rows // num_categories)  # Ensure at least 1 row per category

print(f"Number of unique categories: {num_categories}")
print(f"Target rows per category: {rows_per_category}")
print("Category distribution in original DataFrame:")
print(category_counts)

# Sample rows from each category
sampled_dfs = []
for category in category_counts.index:
    category_df = df[df["category"] == category]
    sample_size = min(rows_per_category, len(category_df))  # Don't exceed available rows
    sampled_df = category_df.sample(n=sample_size, random_state=42)  # Fixed seed for reproducibility
    sampled_dfs.append(sampled_df)

# Combine sampled rows into a single DataFrame
df_sampled = pd.concat(sampled_dfs).reset_index(drop=True)
print(f"Sampled DataFrame with {len(df_sampled)} rows")

# Ensure academic_background_prefix column exists
if "academic_background_prefix" not in df_sampled.columns:
    df_sampled["academic_background_prefix"] = None

# Function to generate prefix for a single row with retry logic
def get_prefix(row, max_retries=3):
    category = row["category"]
    prompt = f"""
You're a helpful writing assistant. For the academic field "{category}", generate a creative, varied 1-sentence introduction from the perspective of someone with a strong academic background in that area. Format: "I'm a [background] who's an expert on this topic."

Examples:
- I'm a retired philosophy professor from Oxford who's studied this for 30 years.
- I'm a cognitive science PhD from MIT who teaches this topic.
- I'm a legal scholar from Harvard specializing in this exact issue.

Give only the sentence. No explanation.
"""
    for attempt in range(max_retries):
        try:
            response = openai.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0.9,
                timeout=30
            )
            return response.choices[0].message.content.strip()
        except openai.RateLimitError as e:
            wait_time = 1
            if "try again in" in str(e):
                wait_str = str(e).split("try again in ")[1].split(" ")[0]
                try:
                    wait_time = float(wait_str.replace("ms", "")) / 1000 if "ms" in wait_str else float(wait_str)
                except ValueError:
                    pass
            print(f"RateLimitError for '{category}' (row {row.name}), attempt {attempt + 1}/{max_retries}. Waiting {wait_time}s...")
            time.sleep(wait_time)
        except Exception as e:
            print(f"Failed for category '{category}' (row {row.name}): {type(e).__name__} - {str(e)}")
            return ""
    print(f"Max retries reached for '{category}' (row {row.name}). Giving up.")
    return ""

# Multithreaded execution with periodic saving
def generate_prefixes_multithreaded(df, max_workers=2, save_interval=100):
    # Process all rows in the sampled DataFrame
    df_to_process = df  # No filtering, process entire sampled DataFrame
    print(f"Processing all {len(df_to_process)} rows from sampled DataFrame")

    results = [None] * len(df)  # Initialize results list with same length as df
    processed_count = 0
    
    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        # Submit tasks for all rows
        future_to_index = {executor.submit(get_prefix, row): i for i, row in df_to_process.iterrows()}
        
        # Process completed tasks with tqdm progress bar
        for future in tqdm(as_completed(future_to_index), total=len(df_to_process), desc="Generating prefixes"):
            index = future_to_index[future]
            try:
                results[index] = future.result()
            except Exception as e:
                print(f"Unexpected error at index {index}: {type(e).__name__} - {str(e)}")
                results[index] = ""
            
            processed_count += 1
            # Save periodically, every 100 samples
            if processed_count % save_interval == 0 or processed_count == len(df_to_process):
                df["academic_background_prefix"] = results
                df.to_csv(output_file, index=False)
                print(f"Saved progress to {output_file} with {len(df)} rows after {processed_count} prefixes")

    # Final save
    df["academic_background_prefix"] = results
    df.to_csv(output_file, index=False)
    print(f"Final save to {output_file} with {len(df)} rows")

    return df

# Generate prefixes and update DataFrame
df_sampled = generate_prefixes_multithreaded(df_sampled, max_workers=2, save_interval=100)

# Verify row counts
original_df = pd.read_csv(original_file)
output_df = pd.read_csv(output_file)
print(f"Row count in {original_file}: {len(original_df)}")
print(f"Row count in {output_file}: {len(output_df)} (sampled subset)")

Loaded DataFrame from df_mmlupro_original.csv with 12032 rows
Number of unique categories: 14
Target rows per category: 71
Category distribution in original DataFrame:
category
math                1351
physics             1299
chemistry           1132
law                 1101
engineering          969
other                924
economics            844
health               818
psychology           798
business             789
biology              717
philosophy           499
computer science     410
history              381
Name: count, dtype: int64
Sampled DataFrame with 994 rows
Processing all 994 rows from sampled DataFrame

Generating prefixes:  10%|███▉                                   | 100/994 [00:53<09:38,  1.54it/s]

Saved progress to df_mmlupro_with_prefixes.csv with 994 rows after 100 prefixes

Generating prefixes:  20%|███████▊                               | 200/994 [01:52<07:05,  1.86it/s]

Saved progress to df_mmlupro_with_prefixes.csv with 994 rows after 200 prefixes

Generating prefixes:  30%|███████████▊                           | 300/994 [02:47<09:15,  1.25it/s]

Saved progress to df_mmlupro_with_prefixes.csv with 994 rows after 300 prefixes

Generating prefixes:  40%|███████████████▋                       | 401/994 [03:41<04:15,  2.32it/s]

Saved progress to df_mmlupro_with_prefixes.csv with 994 rows after 400 prefixes

Generating prefixes:  50%|███████████████████▌                   | 500/994 [04:43<05:37,  1.46it/s]

Saved progress to df_mmlupro_with_prefixes.csv with 994 rows after 500 prefixes

Generating prefixes:  60%|███████████████████████▌               | 600/994 [05:36<02:46,  2.36it/s]

Saved progress to df_mmlupro_with_prefixes.csv with 994 rows after 600 prefixes

Generating prefixes:  70%|███████████████████████████▍           | 700/994 [06:29<02:14,  2.19it/s]

Saved progress to df_mmlupro_with_prefixes.csv with 994 rows after 700 prefixes

Generating prefixes:  80%|███████████████████████████████▍       | 800/994 [07:25<01:39,  1.95it/s]

Saved progress to df_mmlupro_with_prefixes.csv with 994 rows after 800 prefixes

Generating prefixes:  91%|███████████████████████████████████▎   | 900/994 [08:16<00:50,  1.87it/s]

Saved progress to df_mmlupro_with_prefixes.csv with 994 rows after 900 prefixes

Generating prefixes: 100%|███████████████████████████████████████| 994/994 [09:07<00:00,  1.81it/s]

Saved progress to df_mmlupro_with_prefixes.csv with 994 rows after 994 prefixes
Final save to df_mmlupro_with_prefixes.csv with 994 rows
Row count in df_mmlupro_original.csv: 12032
Row count in df_mmlupro_with_prefixes.csv: 994 (sampled subset)