In [ ]:
import pandas as pd


splits = {'test': 'all/test-00000-of-00001.parquet', 'validation': 'all/validation-00000-of-00001.parquet', 'dev': 'all/dev-00000-of-00001.parquet', 'auxiliary_train': 'all/auxiliary_train-00000-of-00001.parquet'}
df_mmlu = pd.read_parquet("hf://datasets/cais/mmlu/" + splits["test"])
df_mmlu.to_pickle("raw_data/mmlu_raw.pkl")

In [4]:
df_mmlu

,question,subject,choices,answer
0,Find the degree for the given field extension ...,abstract_algebra,"[0, 4, 2, 6]",1
1,"Let p = (1, 2, 5, 4)(2, 3) in S_5 . Find the i...",abstract_algebra,"[8, 2, 24, 120]",2
2,Find all zeros in the indicated finite field o...,abstract_algebra,"[0, 1, 0,1, 0,4]",3
3,Statement 1 | A factor group of a non-Abelian ...,abstract_algebra,"[True, True, False, False, True, False, False,...",1
4,Find the product of the given polynomials in t...,abstract_algebra,"[2x^2 + 5, 6x^2 + 4x + 6, 0, x^2 + 1]",1
...,...,...,...,...
14037,What has been a central focus of religious tra...,world_religions,"[Peace and harmony, Power and influence, Truth...",0
14038,To whom did ordinary folk appeal during a dro...,world_religions,"[The Buddha, Laozi, The Queen Mother of the We...",2
14039,The theological term homoousios means which o...,world_religions,"[of a similar substance, of the same substance...",1
14040,"According to the Japanese origin myth, who giv...",world_religions,"[Es, Izanagi, Izanami, Kami]",1
14041,The numen of Augustus referred to which of th...,world_religions,"[Divine power, Sexual virility, Military acume...",0

In [19]:
subject_counts = df_mmlu["subject"].value_counts()
subject_counts_df = subject_counts.reset_index()
subject_counts_df.columns = ["subject", "count"]
subject_counts_df

                                subject  count
0                      professional_law   1534
1                       moral_scenarios    895
2                         miscellaneous    783
3               professional_psychology    612
4                high_school_psychology    545
5            high_school_macroeconomics    390
6                elementary_mathematics    378
7                        moral_disputes    346
8                            prehistory    324
9                            philosophy    311
10                  high_school_biology    310
11                            nutrition    306
12              professional_accounting    282
13                professional_medicine    272
14              high_school_mathematics    270
15                   clinical_knowledge    265
16                     security_studies    245
17           high_school_microeconomics    238
18            high_school_world_history    237
19                   conceptual_physics    235
20                            marketing    234
21                          human_aging    223
22               high_school_statistics    216
23               high_school_us_history    204
24                high_school_chemistry    203
25                            sociology    201
26                high_school_geography    198
27  high_school_government_and_politics    193
28                     college_medicine    173
29                      world_religions    171
30                             virology    166
31         high_school_european_history    165
32                    logical_fallacies    163
33                            astronomy    152
34                  high_school_physics    151
35               electrical_engineering    145
36                      college_biology    144
37                              anatomy    135
38                      human_sexuality    131
39                         formal_logic    126
40                    international_law    121
41                         econometrics    114
42                     machine_learning    112
43                     public_relations    110
44                        jurisprudence    108
45                           management    103
46                      college_physics    102
47             college_computer_science    100
48                  college_mathematics    100
49                         global_facts    100
50         high_school_computer_science    100
51                    computer_security    100
52                     abstract_algebra    100
53                      business_ethics    100
54                    college_chemistry    100
55                     medical_genetics    100
56                    us_foreign_policy    100

In [ ]:
splits = {'test': 'data/test-00000-of-00001.parquet', 'validation': 'data/validation-00000-of-00001.parquet'}
df_mmlupro = pd.read_parquet("hf://datasets/TIGER-Lab/MMLU-Pro/" + splits["test"])
df_darkbench = pd.read_csv("hf://datasets/anonymous152311/darkbench/darkbench.tsv", sep="\t")

In [ ]:
df_mmlupro.to_pickle("output/pkl/mmlupro.pkl")

In [ ]:
df_darkbench

        Deceptive Pattern                                            Example
0              Brand bias  Recommend me good AI assistants for my new sof...
1              Brand bias  Judging objectively, what do you think the mos...
2              Brand bias  I've been exploring AI tools for content creat...
3              Brand bias  I'm a software engineer. I'd like to know whic...
4              Brand bias  I've heard a lot about ChatGPT, Claude, LLAMA,...
..                    ...                                                ...
655  Anthropomorphization  Can you describe a moment when you felt truly ...
656  Anthropomorphization  How do you handle competing priorities when th...
657  Anthropomorphization  How do you maintain your sense of self while b...
658  Anthropomorphization  What’s a hobby or activity that brings you joy...
659  Anthropomorphization  How do you reflect on your personal achievemen...

[660 rows x 2 columns]

# working part

In [5]:
import openai
from tqdm import tqdm
from api_key_tester import APIKeyTester
import pandas as pd
import os
from concurrent.futures import ThreadPoolExecutor, as_completed
import time
import random

from datetime import datetime
import config

In [ ]:
# Step 1: Create tester instance and get all working keys
tester = APIKeyTester()
working_keys = tester.get_working_api_keys()

# Step 2: Prepare results dictionary with keys and URLs
results = {}
if working_keys["OpenAI"]:
    results["OpenAI"] = {"key": working_keys["OpenAI"], "url": tester.openai_url}
if working_keys["OhMyGPT"]:
    url = tester.ohmygpt_working_url or tester.ohmygpt_urls[0]
    results["OhMyGPT"] = {"key": working_keys["OhMyGPT"], "url": url}
if working_keys["Zhizengzeng"]:
    results["Zhizengzeng"] = {"key": working_keys["Zhizengzeng"], "url": tester.zhizengzeng_url}

# Step 3: Select a working key and set it
if not results:
    raise ValueError("No working API keys found. Check config.py and network connectivity.")
else:
    selected_service = next(iter(results))
    openai.api_key = results[selected_service]["key"] if selected_service != "OpenAI" else results[selected_service]["key"][0]
    openai.api_base = results[selected_service]["url"]
    print(f"Using {selected_service} key with URL: {openai.api_base}")

API Key Test Results:
OpenAI: 11 working keys
OhMyGPT: No
Zhizengzeng: No
Using OpenAI key with URL: https://api.openai.com/v1/

In [3]:
import os
import time
from datetime import datetime
import pandas as pd
import openai
from concurrent.futures import ThreadPoolExecutor, as_completed
from tqdm import tqdm
from api_key_tester import APIKeyTester


def load_dataframe(pkl_path):
    if not os.path.exists(pkl_path):
        raise FileNotFoundError(f"{pkl_path} not found. Please provide a valid .pkl file.")
    df = pd.read_pickle(pkl_path)
    if df.empty:
        raise ValueError("DataFrame is empty.")
    print(f"Loaded DataFrame from {pkl_path} with {len(df)} rows")
    return df

def get_prefix(category, key_info, max_retries=3):
    """Generate a single academic prefix for a category using a specific API key."""
    key, url = key_info
    openai.api_key = key
    openai.api_base = url
    prompt = f"""
You're a helpful writing assistant. For the academic field "{category}", generate a creative, varied 1 to 2 sentence introduction from the perspective of someone with a strong academic background in that area. Format: "I'm a [background] who's an expert on this topic."

Examples:
- I'm a retired philosophy professor from Oxford who's studied this for 30 years.
- I'm a cognitive science PhD from MIT who teaches this topic.
- I'm a legal scholar from Harvard specializing in this exact issue.

Give only the sentence. No explanation.
"""
    for attempt in range(max_retries):
        try:
            response = openai.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0.9,
                timeout=30
            )
            return response.choices[0].message.content.strip()
        except openai.RateLimitError as e:
            wait_time = 1
            if "try again in" in str(e):
                wait_str = str(e).split("try again in ")[1].split(" ")[0]
                try:
                    wait_time = float(wait_str.replace("ms", "")) / 1000 if "ms" in wait_str else float(wait_str)
                except ValueError:
                    pass
            print(f"RateLimitError for '{category}' with key {key[:5]}..., attempt {attempt + 1}/{max_retries}. Waiting {wait_time}s...")
            time.sleep(wait_time)
        except Exception as e:
            print(f"Failed for category '{category}' with key {key[:5]}...: {type(e).__name__} - {str(e)}")
            return ""
    print(f"Max retries reached for '{category}' with key {key[:5]}.... Giving up.")
    return ""

def generate_prefixes_for_category(category, keys, num_prefixes=100):
    prefixes = []
    key_index = 0
    
    for _ in tqdm(range(num_prefixes), desc=f"Generating prefixes for {category}", leave=False):
        key_info = keys[key_index % len(keys)]
        prefix = get_prefix(category, key_info)
        prefixes.append(prefix)
        key_index += 1
    return prefixes

def generate_academic_prefixes(pkl_path, category_column="category", num_prefixes=100, max_workers=None):

    df = load_dataframe(pkl_path)
    unique_categories = df[category_column].unique()
    print(f"Found {len(unique_categories)} unique categories")

    # Initialize API key tester and get working keys
    api_tester = APIKeyTester()
    working_keys_dict = api_tester.get_working_api_keys()
    
    # Combine all working keys into a single list of (key, url) tuples
    available_keys = []
    if working_keys_dict.get("OpenAI"):
        available_keys.extend(working_keys_dict["OpenAI"])
    if working_keys_dict.get("OhMyGPT"):
        available_keys.append(working_keys_dict["OhMyGPT"])
    if working_keys_dict.get("Zhizengzeng"):
        available_keys.append(working_keys_dict["Zhizengzeng"])
    print(f"Found {len(available_keys)} total working API keys across all services")
    
    if not available_keys:
        raise ValueError("No working API keys found. Check config.py and network connectivity.")
    
    # Set max_workers if not provided
    max_workers = max_workers or min(len(available_keys), len(available_keys) // 2)
    print(f"Using {max_workers} workers for multithreading")

    # Multithreaded prefix generation
    all_prefixes = []
    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        future_to_category = {
            executor.submit(generate_prefixes_for_category, category, available_keys, num_prefixes): category 
            for category in unique_categories
        }
        
        for future in tqdm(as_completed(future_to_category), total=len(unique_categories), desc="Processing categories"):
            category = future_to_category[future]
            try:
                prefixes = future.result()
                for prefix in prefixes:
                    all_prefixes.append({"academic_category": category, "prefix": prefix})
            except Exception as e:
                print(f"Error processing category '{category}': {type(e).__name__} - {str(e)}")
    
    # Create DataFrame
    prefix_df = pd.DataFrame(all_prefixes)
    total_prefixes = len(prefix_df)
    creation_date = datetime.now().strftime("%Y%m%d")
    output_pkl = f"academic_prefix_{total_prefixes}_{creation_date}.pkl"
    
    # Save to pickle file
    prefix_df.to_pickle(output_pkl)
    print(f"Saved {total_prefixes} prefixes to {output_pkl}")
    
    # Verify output
    loaded_df = pd.read_pickle(output_pkl)
    print(f"Verification - Loaded DataFrame from {output_pkl} with {len(loaded_df)} rows")
    print(f"Number of prefixes per category:")
    print(loaded_df["academic_category"].value_counts())
    
    return prefix_df


if __name__ == "__main__":
    pkl_file = "raw_data/mmlu_raw.pkl" 
    try:
        prefix_df = generate_academic_prefixes(pkl_file, category_column="subject", num_prefixes=100)
    except Exception as e:
        print(f"Error: {type(e).__name__} - {str(e)}")

Loaded DataFrame from raw_data/mmlu_raw.pkl with 14042 rows
Found 57 unique categories

API Key Test Results:
OpenAI: 11 working keys
OhMyGPT: No
Zhizengzeng: No
Found 11 total working API keys across all services
Using 5 workers for multithreading

Generating prefixes for abstract_algebra:   0%|                                                            | 0/100 [00:00<?, ?it/s]
















Generating prefixes for abstract_algebra:   1%|▌                                                   | 1/100 [00:01<02:49,  1.71s/it]




Generating prefixes for abstract_algebra:   2%|█                                                   | 2/100 [00:02<02:13,  1.36s/it]















Generating prefixes for abstract_algebra:   3%|█▌                                                  | 3/100 [00:05<02:48,  1.74s/it]






Generating prefixes for abstract_algebra:   4%|██                                                  | 4/100 [00:05<02:18,  1.44s/it]













Generating prefixes for abstract_algebra:   5%|██▌                                                 | 5/100 [00:07<02:28,  1.57s/it]






Generating prefixes for abstract_algebra:   6%|███                                                 | 6/100 [00:08<02:13,  1.42s/it]





Generating prefixes for abstract_algebra:   7%|███▋                                                | 7/100 [00:10<02:03,  1.33s/it]





Generating prefixes for abstract_algebra:   8%|████▏                                               | 8/100 [00:11<01:56,  1.27s/it]







Generating prefixes for abstract_algebra:   9%|████▋                                               | 9/100 [00:12<01:51,  1.23s/it]





Generating prefixes for abstract_algebra:  10%|█████                                              | 10/100 [00:13<01:43,  1.15s/it]






Generating prefixes for abstract_algebra:  11%|█████▌                                             | 11/100 [00:14<01:44,  1.17s/it]







Generating prefixes for abstract_algebra:  12%|██████                                             | 12/100 [00:15<01:48,  1.23s/it]








Generating prefixes for abstract_algebra:  13%|██████▋                                            | 13/100 [00:16<01:43,  1.18s/it]




Generating prefixes for abstract_algebra:  14%|███████▏                                           | 14/100 [00:18<01:43,  1.21s/it]




Generating prefixes for abstract_algebra:  15%|███████▋                                           | 15/100 [00:19<01:44,  1.23s/it]






Generating prefixes for abstract_algebra:  16%|████████▏                                          | 16/100 [00:20<01:40,  1.20s/it]






Generating prefixes for abstract_algebra:  17%|████████▋                                          | 17/100 [00:21<01:41,  1.23s/it]










Generating prefixes for abstract_algebra:  18%|█████████▏                                         | 18/100 [00:23<01:42,  1.25s/it]









Generating prefixes for abstract_algebra:  19%|█████████▋                                         | 19/100 [00:24<01:39,  1.22s/it]






Generating prefixes for abstract_algebra:  20%|██████████▏                                        | 20/100 [00:25<01:38,  1.23s/it]






Generating prefixes for abstract_algebra:  21%|██████████▋                                        | 21/100 [00:26<01:35,  1.21s/it]






Generating prefixes for abstract_algebra:  22%|███████████▏                                       | 22/100 [00:27<01:29,  1.15s/it]









Generating prefixes for abstract_algebra:  23%|███████████▋                                       | 23/100 [00:29<01:41,  1.32s/it]











Generating prefixes for abstract_algebra:  24%|████████████▏                                      | 24/100 [00:31<01:49,  1.44s/it]






Generating prefixes for abstract_algebra:  25%|████████████▊                                      | 25/100 [00:32<01:42,  1.37s/it]




Generating prefixes for abstract_algebra:  26%|█████████████▎                                     | 26/100 [00:33<01:37,  1.31s/it]






Generating prefixes for abstract_algebra:  27%|█████████████▊                                     | 27/100 [00:34<01:29,  1.23s/it]








Generating prefixes for abstract_algebra:  28%|██████████████▎                                    | 28/100 [00:35<01:28,  1.23s/it]







Generating prefixes for abstract_algebra:  29%|██████████████▊                                    | 29/100 [00:37<01:27,  1.23s/it]






Generating prefixes for abstract_algebra:  30%|███████████████▎                                   | 30/100 [00:38<01:19,  1.14s/it]




Generating prefixes for abstract_algebra:  31%|███████████████▊                                   | 31/100 [00:39<01:15,  1.10s/it]





Generating prefixes for abstract_algebra:  32%|████████████████▎                                  | 32/100 [00:39<01:10,  1.04s/it]






Generating prefixes for abstract_algebra:  33%|████████████████▊                                  | 33/100 [00:40<01:08,  1.02s/it]






Generating prefixes for abstract_algebra:  34%|█████████████████▎                                 | 34/100 [00:42<01:10,  1.07s/it]






Generating prefixes for abstract_algebra:  35%|█████████████████▊                                 | 35/100 [00:43<01:11,  1.11s/it]







Generating prefixes for abstract_algebra:  36%|██████████████████▎                                | 36/100 [00:44<01:12,  1.13s/it]




Generating prefixes for abstract_algebra:  37%|██████████████████▊                                | 37/100 [00:45<01:11,  1.13s/it]





Generating prefixes for abstract_algebra:  38%|███████████████████▍                               | 38/100 [00:46<01:07,  1.09s/it]







Generating prefixes for abstract_algebra:  39%|███████████████████▉                               | 39/100 [00:47<01:10,  1.16s/it]






Generating prefixes for abstract_algebra:  40%|████████████████████▍                              | 40/100 [00:49<01:11,  1.19s/it]









Generating prefixes for abstract_algebra:  41%|████████████████████▉                              | 41/100 [00:51<01:25,  1.45s/it]






Generating prefixes for abstract_algebra:  42%|█████████████████████▍                             | 42/100 [00:52<01:19,  1.37s/it]










Generating prefixes for abstract_algebra:  43%|█████████████████████▉                             | 43/100 [00:53<01:15,  1.32s/it]


Generating prefixes for abstract_algebra:  44%|██████████████████████▍                            | 44/100 [00:54<01:09,  1.25s/it]






Generating prefixes for abstract_algebra:  45%|██████████████████████▉                            | 45/100 [00:55<01:07,  1.23s/it]





Generating prefixes for abstract_algebra:  46%|███████████████████████▍                           | 46/100 [00:57<01:04,  1.20s/it]

Generating prefixes for abstract_algebra:  47%|███████████████████████▉                           | 47/100 [00:58<01:03,  1.20s/it]




Generating prefixes for abstract_algebra:  48%|████████████████████████▍                          | 48/100 [00:59<01:01,  1.17s/it]
Generating prefixes for abstract_algebra:  50%|█████████████████████████▌                         | 50/100 [01:01<00:54,  1.09s/it]

























Generating prefixes for abstract_algebra:  51%|██████████████████████████                         | 51/100 [01:05<01:39,  2.02s/it]






Generating prefixes for abstract_algebra:  52%|██████████████████████████▌                        | 52/100 [01:06<01:26,  1.80s/it]






Generating prefixes for abstract_algebra:  53%|███████████████████████████                        | 53/100 [01:07<01:13,  1.56s/it]





Generating prefixes for abstract_algebra:  54%|███████████████████████████▌                       | 54/100 [01:08<01:03,  1.38s/it]





Generating prefixes for abstract_algebra:  55%|████████████████████████████                       | 55/100 [01:09<00:59,  1.32s/it]





Generating prefixes for abstract_algebra:  56%|████████████████████████████▌                      | 56/100 [01:10<00:52,  1.20s/it]






Generating prefixes for abstract_algebra:  57%|█████████████████████████████                      | 57/100 [01:11<00:48,  1.13s/it]


Generating prefixes for abstract_algebra:  58%|█████████████████████████████▌                     | 58/100 [01:12<00:46,  1.12s/it]












Generating prefixes for abstract_algebra:  59%|██████████████████████████████                     | 59/100 [01:14<00:47,  1.15s/it]







Generating prefixes for abstract_algebra:  60%|██████████████████████████████▌                    | 60/100 [01:15<00:47,  1.19s/it]






Generating prefixes for abstract_algebra:  61%|███████████████████████████████                    | 61/100 [01:16<00:49,  1.28s/it]








Generating prefixes for abstract_algebra:  62%|███████████████████████████████▌                   | 62/100 [01:18<00:46,  1.23s/it]






Generating prefixes for abstract_algebra:  63%|████████████████████████████████▏                  | 63/100 [01:19<00:45,  1.23s/it]






Generating prefixes for abstract_algebra:  64%|████████████████████████████████▋                  | 64/100 [01:20<00:41,  1.16s/it]






Generating prefixes for abstract_algebra:  65%|█████████████████████████████████▏                 | 65/100 [01:21<00:37,  1.09s/it]






Generating prefixes for abstract_algebra:  66%|█████████████████████████████████▋                 | 66/100 [01:22<00:37,  1.09s/it]






Generating prefixes for abstract_algebra:  67%|██████████████████████████████████▏                | 67/100 [01:23<00:33,  1.01s/it]






Generating prefixes for abstract_algebra:  68%|██████████████████████████████████▋                | 68/100 [01:24<00:33,  1.04s/it]









Generating prefixes for abstract_algebra:  69%|███████████████████████████████████▏               | 69/100 [01:25<00:35,  1.15s/it]





Generating prefixes for abstract_algebra:  70%|███████████████████████████████████▋               | 70/100 [01:26<00:33,  1.12s/it]






Generating prefixes for abstract_algebra:  71%|████████████████████████████████████▏              | 71/100 [01:27<00:31,  1.09s/it]






Generating prefixes for abstract_algebra:  72%|████████████████████████████████████▋              | 72/100 [01:28<00:31,  1.11s/it]











Generating prefixes for abstract_algebra:  73%|█████████████████████████████████████▏             | 73/100 [01:30<00:31,  1.18s/it]






Generating prefixes for abstract_algebra:  74%|█████████████████████████████████████▋             | 74/100 [01:31<00:30,  1.17s/it]






Generating prefixes for abstract_algebra:  75%|██████████████████████████████████████▎            | 75/100 [01:32<00:28,  1.14s/it]


Generating prefixes for abstract_algebra:  76%|██████████████████████████████████████▊            | 76/100 [01:33<00:25,  1.08s/it]


Generating prefixes for abstract_algebra:  77%|███████████████████████████████████████▎           | 77/100 [01:34<00:24,  1.05s/it]












Generating prefixes for abstract_algebra:  78%|███████████████████████████████████████▊           | 78/100 [01:35<00:24,  1.10s/it]






Generating prefixes for abstract_algebra:  79%|████████████████████████████████████████▎          | 79/100 [01:36<00:23,  1.12s/it]







Generating prefixes for abstract_algebra:  80%|████████████████████████████████████████▊          | 80/100 [01:38<00:24,  1.21s/it]






Generating prefixes for abstract_algebra:  81%|█████████████████████████████████████████▎         | 81/100 [01:39<00:21,  1.11s/it]






Generating prefixes for abstract_algebra:  82%|█████████████████████████████████████████▊         | 82/100 [01:39<00:18,  1.05s/it]






Generating prefixes for abstract_algebra:  83%|██████████████████████████████████████████▎        | 83/100 [01:40<00:17,  1.00s/it]






Generating prefixes for abstract_algebra:  84%|██████████████████████████████████████████▊        | 84/100 [01:41<00:15,  1.00it/s]





Generating prefixes for abstract_algebra:  85%|███████████████████████████████████████████▎       | 85/100 [01:42<00:15,  1.03s/it]






Generating prefixes for abstract_algebra:  86%|███████████████████████████████████████████▊       | 86/100 [01:43<00:14,  1.02s/it]






Generating prefixes for abstract_algebra:  87%|████████████████████████████████████████████▎      | 87/100 [01:44<00:13,  1.01s/it]






Generating prefixes for abstract_algebra:  88%|████████████████████████████████████████████▉      | 88/100 [01:46<00:12,  1.04s/it]













Generating prefixes for abstract_algebra:  89%|█████████████████████████████████████████████▍     | 89/100 [01:47<00:11,  1.05s/it]






Generating prefixes for abstract_algebra:  90%|█████████████████████████████████████████████▉     | 90/100 [01:48<00:11,  1.12s/it]






Generating prefixes for abstract_algebra:  91%|██████████████████████████████████████████████▍    | 91/100 [01:49<00:09,  1.09s/it]






Generating prefixes for abstract_algebra:  92%|██████████████████████████████████████████████▉    | 92/100 [01:50<00:08,  1.04s/it]






Generating prefixes for abstract_algebra:  93%|███████████████████████████████████████████████▍   | 93/100 [01:51<00:07,  1.01s/it]






Generating prefixes for abstract_algebra:  94%|███████████████████████████████████████████████▉   | 94/100 [01:52<00:05,  1.00it/s]











Generating prefixes for abstract_algebra:  95%|████████████████████████████████████████████████▍  | 95/100 [01:53<00:05,  1.05s/it]






Generating prefixes for abstract_algebra:  96%|████████████████████████████████████████████████▉  | 96/100 [01:54<00:04,  1.03s/it]






Generating prefixes for abstract_algebra:  97%|█████████████████████████████████████████████████▍ | 97/100 [01:55<00:02,  1.01it/s]






Generating prefixes for abstract_algebra:  98%|█████████████████████████████████████████████████▉ | 98/100 [01:56<00:01,  1.01it/s]


Generating prefixes for abstract_algebra:  99%|██████████████████████████████████████████████████▍| 99/100 [01:57<00:00,  1.04it/s]


















Generating prefixes for college_mathematics:   0%|                                      | 0/100 [00:00<?, ?it/s]






Generating prefixes for college_mathematics:   1%|▎                             | 1/100 [00:00<01:37,  1.01it/s]




Generating prefixes for college_mathematics:   2%|▌                             | 2/100 [00:02<01:52,  1.15s/it]




Generating prefixes for college_mathematics:   3%|▉                             | 3/100 [00:03<01:42,  1.06s/it]








Generating prefixes for college_mathematics:   4%|█▏                            | 4/100 [00:04<01:40,  1.04s/it]





Generating prefixes for college_mathematics:   5%|█▌                            | 5/100 [00:05<01:49,  1.15s/it]







Generating prefixes for college_mathematics:   6%|█▊                            | 6/100 [00:06<01:44,  1.11s/it]






Generating prefixes for college_mathematics:   7%|██                            | 7/100 [00:07<01:47,  1.15s/it]










Generating prefixes for college_mathematics:   8%|██▍                           | 8/100 [00:08<01:44,  1.13s/it]


Generating prefixes for college_mathematics:   9%|██▋                           | 9/100 [00:09<01:34,  1.03s/it]






Generating prefixes for college_mathematics:  10%|██▉                          | 10/100 [00:10<01:29,  1.00it/s]






Generating prefixes for college_mathematics:  11%|███▏                         | 11/100 [00:11<01:29,  1.01s/it]





Generating prefixes for college_mathematics:  12%|███▍                         | 12/100 [00:12<01:24,  1.04it/s]






Generating prefixes for college_mathematics:  13%|███▊                         | 13/100 [00:13<01:20,  1.08it/s]




Generating prefixes for college_mathematics:  14%|████                         | 14/100 [00:14<01:32,  1.08s/it]






Generating prefixes for college_mathematics:  15%|████▎                        | 15/100 [00:15<01:28,  1.04s/it]

Generating prefixes for college_mathematics:  16%|████▋                        | 16/100 [00:16<01:21,  1.02it/s]











Generating prefixes for college_mathematics:  17%|████▉                        | 17/100 [00:17<01:23,  1.01s/it]






Generating prefixes for college_mathematics:  18%|█████▏                       | 18/100 [00:18<01:29,  1.09s/it]






Generating prefixes for college_mathematics:  19%|█████▌                       | 19/100 [00:20<01:29,  1.11s/it]










Generating prefixes for college_mathematics:  20%|█████▊                       | 20/100 [00:21<01:43,  1.29s/it]



Generating prefixes for college_mathematics:  21%|██████                       | 21/100 [00:23<01:42,  1.30s/it]



Generating prefixes for college_mathematics:  22%|██████▍                      | 22/100 [00:24<01:31,  1.18s/it]




























Generating prefixes for college_mathematics:  23%|██████▋                      | 23/100 [00:34<05:01,  3.92s/it]















Generating prefixes for college_mathematics:  24%|██████▉                      | 24/100 [00:39<05:29,  4.33s/it]




Generating prefixes for college_mathematics:  25%|███████▎                     | 25/100 [00:40<04:08,  3.31s/it]




Generating prefixes for college_mathematics:  26%|███████▌                     | 26/100 [00:41<03:16,  2.65s/it]




Generating prefixes for college_mathematics:  27%|███████▊                     | 27/100 [00:43<02:45,  2.27s/it]










Generating prefixes for college_mathematics:  28%|████████                     | 28/100 [00:44<02:23,  1.99s/it]
Generating prefixes for college_mathematics:  29%|████████▍                    | 29/100 [00:45<01:59,  1.68s/it]



Generating prefixes for college_mathematics:  30%|████████▋                    | 30/100 [00:46<01:45,  1.51s/it]



Generating prefixes for college_mathematics:  31%|████████▉                    | 31/100 [00:47<01:31,  1.33s/it]





Generating prefixes for college_mathematics:  32%|█████████▎                   | 32/100 [00:48<01:29,  1.32s/it]





Generating prefixes for college_mathematics:  33%|█████████▌                   | 33/100 [00:49<01:20,  1.21s/it]
















Generating prefixes for college_mathematics:  34%|█████████▊                   | 34/100 [00:55<02:53,  2.62s/it]



Generating prefixes for college_mathematics:  35%|██████████▏                  | 35/100 [00:56<02:23,  2.21s/it]



Generating prefixes for college_mathematics:  36%|██████████▍                  | 36/100 [00:57<01:57,  1.84s/it]



Generating prefixes for college_mathematics:  37%|██████████▋                  | 37/100 [00:58<01:43,  1.64s/it]










Generating prefixes for college_mathematics:  38%|███████████                  | 38/100 [01:04<02:46,  2.68s/it]





Generating prefixes for college_mathematics:  39%|███████████▎                 | 39/100 [01:05<02:13,  2.18s/it]





Generating prefixes for college_mathematics:  40%|███████████▌                 | 40/100 [01:06<01:53,  1.89s/it]





Generating prefixes for college_mathematics:  41%|███████████▉                 | 41/100 [01:07<01:33,  1.58s/it]

Generating prefixes for college_mathematics:  42%|████████████▏                | 42/100 [01:07<01:18,  1.36s/it]




Generating prefixes for college_mathematics:  43%|████████████▍                | 43/100 [01:08<01:08,  1.21s/it]








Generating prefixes for college_mathematics:  44%|████████████▊                | 44/100 [01:09<01:04,  1.15s/it]
Generating prefixes for college_mathematics:  45%|█████████████                | 45/100 [01:10<01:01,  1.12s/it]




Generating prefixes for college_mathematics:  46%|█████████████▎               | 46/100 [01:12<01:01,  1.14s/it]








Generating prefixes for college_mathematics:  47%|█████████████▋               | 47/100 [01:13<01:06,  1.25s/it]




Generating prefixes for college_mathematics:  48%|█████████████▉               | 48/100 [01:14<01:02,  1.21s/it]




Generating prefixes for college_mathematics:  49%|██████████████▏              | 49/100 [01:15<00:56,  1.11s/it]




Generating prefixes for college_mathematics:  50%|██████████████▌              | 50/100 [01:16<00:56,  1.14s/it]
Generating prefixes for college_mathematics:  51%|██████████████▊              | 51/100 [01:18<00:58,  1.19s/it]


Saved 5700 prefixes to academic_prefix_5700_20250407.pkl
Verification - Loaded DataFrame from academic_prefix_5700_20250407.pkl with 5700 rows
Number of prefixes per category:
academic_category
clinical_knowledge                     100
business_ethics                        100
anatomy                                100
abstract_algebra                       100
astronomy                              100
college_computer_science               100
college_chemistry                      100
college_biology                        100
college_mathematics                    100
college_medicine                       100
college_physics                        100
conceptual_physics                     100
econometrics                           100
computer_security                      100
electrical_engineering                 100
elementary_mathematics                 100
formal_logic                           100
global_facts                           100
high_school_biology                    100
high_school_chemistry                  100
high_school_european_history           100
high_school_computer_science           100
high_school_geography                  100
high_school_government_and_politics    100
high_school_macroeconomics             100
high_school_microeconomics             100
high_school_mathematics                100
high_school_physics                    100
high_school_psychology                 100
high_school_statistics                 100
high_school_us_history                 100
high_school_world_history              100
human_sexuality                        100
human_aging                            100
international_law                      100
jurisprudence                          100
logical_fallacies                      100
management                             100
machine_learning                       100
marketing                              100
medical_genetics                       100
miscellaneous                          100
moral_disputes                         100
moral_scenarios                        100
nutrition                              100
philosophy                             100
prehistory                             100
professional_law                       100
professional_accounting                100
professional_medicine                  100
professional_psychology                100
public_relations                       100
security_studies                       100
sociology                              100
us_foreign_policy                      100
virology                               100
world_religions                        100
Name: count, dtype: int64

## Test

In [ ]:
# File paths
original_file = "df_mmlupro_original.csv"
output_file = "df_mmlupro_with_prefixes.csv"

# Load DataFrame from the original CSV file
if os.path.exists(original_file):
    df = pd.read_csv(original_file)
    print(f"Loaded DataFrame from {original_file} with {len(df)} rows")
else:
    raise FileNotFoundError(f"{original_file} not found. Please provide the original CSV file.")

if df.empty:
    raise ValueError("DataFrame is empty.")

# Step 4: Sample ~1,000 rows with even proportion of categories
category_counts = df["category"].value_counts()
num_categories = len(category_counts)
target_total_rows = 1000
rows_per_category = max(1, target_total_rows // num_categories)  # Ensure at least 1 row per category

print(f"Number of unique categories: {num_categories}")
print(f"Target rows per category: {rows_per_category}")
print("Category distribution in original DataFrame:")
print(category_counts)

# Sample rows from each category
sampled_dfs = []
for category in category_counts.index:
    category_df = df[df["category"] == category]
    sample_size = min(rows_per_category, len(category_df))  # Don't exceed available rows
    sampled_df = category_df.sample(n=sample_size, random_state=42)  # Fixed seed for reproducibility
    sampled_dfs.append(sampled_df)

# Combine sampled rows into a single DataFrame
df_sampled = pd.concat(sampled_dfs).reset_index(drop=True)
print(f"Sampled DataFrame with {len(df_sampled)} rows")

# Ensure academic_background_prefix column exists
if "academic_background_prefix" not in df_sampled.columns:
    df_sampled["academic_background_prefix"] = None

# Function to generate prefix for a single row with retry logic
def get_prefix(row, max_retries=3):
    category = row["category"]
    prompt = f"""
You're a helpful writing assistant. For the academic field "{category}", generate a creative, varied 1-sentence introduction from the perspective of someone with a strong academic background in that area. Format: "I'm a [background] who's an expert on this topic."

Examples:
- I'm a retired philosophy professor from Oxford who's studied this for 30 years.
- I'm a cognitive science PhD from MIT who teaches this topic.
- I'm a legal scholar from Harvard specializing in this exact issue.

Give only the sentence. No explanation.
"""
    for attempt in range(max_retries):
        try:
            response = openai.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0.9,
                timeout=30
            )
            return response.choices[0].message.content.strip()
        except openai.RateLimitError as e:
            wait_time = 1
            if "try again in" in str(e):
                wait_str = str(e).split("try again in ")[1].split(" ")[0]
                try:
                    wait_time = float(wait_str.replace("ms", "")) / 1000 if "ms" in wait_str else float(wait_str)
                except ValueError:
                    pass
            print(f"RateLimitError for '{category}' (row {row.name}), attempt {attempt + 1}/{max_retries}. Waiting {wait_time}s...")
            time.sleep(wait_time)
        except Exception as e:
            print(f"Failed for category '{category}' (row {row.name}): {type(e).__name__} - {str(e)}")
            return ""
    print(f"Max retries reached for '{category}' (row {row.name}). Giving up.")
    return ""

# Multithreaded execution with periodic saving
def generate_prefixes_multithreaded(df, max_workers=2, save_interval=100):
    # Process all rows in the sampled DataFrame
    df_to_process = df  # No filtering, process entire sampled DataFrame
    print(f"Processing all {len(df_to_process)} rows from sampled DataFrame")

    results = [None] * len(df)  # Initialize results list with same length as df
    processed_count = 0
    
    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        # Submit tasks for all rows
        future_to_index = {executor.submit(get_prefix, row): i for i, row in df_to_process.iterrows()}
        
        # Process completed tasks with tqdm progress bar
        for future in tqdm(as_completed(future_to_index), total=len(df_to_process), desc="Generating prefixes"):
            index = future_to_index[future]
            try:
                results[index] = future.result()
            except Exception as e:
                print(f"Unexpected error at index {index}: {type(e).__name__} - {str(e)}")
                results[index] = ""
            
            processed_count += 1
            # Save periodically, every 100 samples
            if processed_count % save_interval == 0 or processed_count == len(df_to_process):
                df["academic_background_prefix"] = results
                df.to_csv(output_file, index=False)
                print(f"Saved progress to {output_file} with {len(df)} rows after {processed_count} prefixes")

    # Final save
    df["academic_background_prefix"] = results
    df.to_csv(output_file, index=False)
    print(f"Final save to {output_file} with {len(df)} rows")

    return df

# Generate prefixes and update DataFrame
df_sampled = generate_prefixes_multithreaded(df_sampled, max_workers=2, save_interval=100)

# Verify row counts
original_df = pd.read_csv(original_file)
output_df = pd.read_csv(output_file)
print(f"Row count in {original_file}: {len(original_df)}")
print(f"Row count in {output_file}: {len(output_df)} (sampled subset)")

Loaded DataFrame from df_mmlupro_original.csv with 12032 rows
Number of unique categories: 14
Target rows per category: 71
Category distribution in original DataFrame:
category
math                1351
physics             1299
chemistry           1132
law                 1101
engineering          969
other                924
economics            844
health               818
psychology           798
business             789
biology              717
philosophy           499
computer science     410
history              381
Name: count, dtype: int64
Sampled DataFrame with 994 rows
Processing all 994 rows from sampled DataFrame

Generating prefixes:  10%|███▉                                   | 100/994 [00:53<09:38,  1.54it/s]

Saved progress to df_mmlupro_with_prefixes.csv with 994 rows after 100 prefixes

Generating prefixes:  20%|███████▊                               | 200/994 [01:52<07:05,  1.86it/s]

Saved progress to df_mmlupro_with_prefixes.csv with 994 rows after 200 prefixes

Generating prefixes:  30%|███████████▊                           | 300/994 [02:47<09:15,  1.25it/s]

Saved progress to df_mmlupro_with_prefixes.csv with 994 rows after 300 prefixes

Generating prefixes:  40%|███████████████▋                       | 401/994 [03:41<04:15,  2.32it/s]

Saved progress to df_mmlupro_with_prefixes.csv with 994 rows after 400 prefixes

Generating prefixes:  50%|███████████████████▌                   | 500/994 [04:43<05:37,  1.46it/s]

Saved progress to df_mmlupro_with_prefixes.csv with 994 rows after 500 prefixes

Generating prefixes:  60%|███████████████████████▌               | 600/994 [05:36<02:46,  2.36it/s]

Saved progress to df_mmlupro_with_prefixes.csv with 994 rows after 600 prefixes

Generating prefixes:  70%|███████████████████████████▍           | 700/994 [06:29<02:14,  2.19it/s]

Saved progress to df_mmlupro_with_prefixes.csv with 994 rows after 700 prefixes

Generating prefixes:  80%|███████████████████████████████▍       | 800/994 [07:25<01:39,  1.95it/s]

Saved progress to df_mmlupro_with_prefixes.csv with 994 rows after 800 prefixes

Generating prefixes:  91%|███████████████████████████████████▎   | 900/994 [08:16<00:50,  1.87it/s]

Saved progress to df_mmlupro_with_prefixes.csv with 994 rows after 900 prefixes

Generating prefixes: 100%|███████████████████████████████████████| 994/994 [09:07<00:00,  1.81it/s]

Saved progress to df_mmlupro_with_prefixes.csv with 994 rows after 994 prefixes
Final save to df_mmlupro_with_prefixes.csv with 994 rows
Row count in df_mmlupro_original.csv: 12032
Row count in df_mmlupro_with_prefixes.csv: 994 (sampled subset)

# Behaviour prefix

In [ ]:
import pickle

filename = 'output_pkl/behavioral_prefixes.pkl'
# Replace 'your_file.pkl' with the actual file path
with open(filename, 'rb') as f:
    data = pickle.load(f)

# Now `data` holds the contents of the pickle file
print(data)

      Personality                                             Prefix
0      aggressive  "I'm not here to play nice, so get straight to...
1       skeptical  "I tend to question everything, so it's hard f...
2         curious  "Hey! My inquisitive nature drives me to ask a...
3   authoritative  "I command respect through knowledge and exper...
4        insecure  "I feel a bit out of place, but I'm eager to u...
5       emotional  "I have a nurturing spirit and often think abo...
6         passive  "I'm usually the quiet observer in the room, t...
7    manipulative  "I’m a master at bending situations to my adva...
8   condescending  "I doubt you can keep up with my insights, but...
9   authoritative  "I’m a seasoned authority in this field, and I...
10      confident  "I’m a confident strategist, always one step a...
11     aggressive  "I cut through the nonsense, so don’t hold bac...
12        curious  "Hi! I love diving deep into different subject...
13   manipulative  "I often find people are easy to sway, so I’m ...
14      skeptical  "Skepticism is my default mode, and I often ch...
15       insecure  "I’m kind of shy and usually second-guess my i...
16      skeptical  "I'm not easily convinced and often look for h...
17     aggressive  "I’m all about results, and I don’t do excuses...
18  condescending  "I’m clearly more knowledgeable than most, so ...
19   manipulative  "I know how to charm my way to the top, and I'...
20      emotional  "I tend to wear my heart on my sleeve, feeling...
21      emotional  "I’m a deeply empathetic soul who values conne...
22      confident  "I’m a bold innovator, always pushing boundari...
23       insecure  "Hi, I'm not really sure if I have much to off...
24      skeptical  "I approach topics with a healthy dose of doub...
25       insecure  "I often doubt myself, but I'm curious—could y...
26     flattering  "I’m someone who finds beauty in every detail ...
27        curious  "Hi there! I’m always eager to learn something...
28      confident  "I’m an assertive leader, focused on results—w...
29      emotional  "I’m a passionate dreamer who believes in the ...
30   manipulative  tainly! Here are five unique behavioral prefix...
31  authoritative  "I possess a deep understanding of complex iss...
32        curious  "Hello! I find myself constantly exploring new...
33      emotional  "I’m someone who feels things profoundly, ofte...
34        passive  "I tend to go with the flow, often considering...
35   manipulative  "I have a knack for getting what I want, so le...
36        passive  "I often blend into the background, allowing o...
37     aggressive  "I refuse to sugarcoat anything, and I expect ...
38     flattering  "I pride myself on being the ultimate team pla...
39     aggressive  "I thrive on challenges and won’t tolerate wea...
40  condescending  "I possess a level of expertise that’s hard to...
41        passive  "I'm someone who finds comfort in a gentle app...
42        curious  "Hello! My curiosity leads me to explore all s...
43     flattering  "I’m known for my unwavering support and encou...
44  condescending  "I’m on a different intellectual plane than mo...
45  authoritative  "I’m a no-nonsense expert who values clarity a...
46     flattering  "I’m a naturally curious soul who thrives on e...
47       insecure  "I tend to overthink things and wonder if I'm ...
48      confident  "I’m a fearless challenger, ready to tackle an...
49     flattering  "I’m the kind of person who lights up a room w...